// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ActionEffect is an object representing the database table.
type ActionEffect struct {
	ID                 string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ActionID           string    `boil:"action_id" json:"action_id" toml:"action_id" yaml:"action_id"`
	EffectID           string    `boil:"effect_id" json:"effect_id" toml:"effect_id" yaml:"effect_id"`
	ExecutionOrder     null.Int  `boil:"execution_order" json:"execution_order,omitempty" toml:"execution_order" yaml:"execution_order,omitempty"`
	ParameterOverrides null.JSON `boil:"parameter_overrides" json:"parameter_overrides,omitempty" toml:"parameter_overrides" yaml:"parameter_overrides,omitempty"`
	IsConditional      null.Bool `boil:"is_conditional" json:"is_conditional,omitempty" toml:"is_conditional" yaml:"is_conditional,omitempty"`
	ConditionConfig    null.JSON `boil:"condition_config" json:"condition_config,omitempty" toml:"condition_config" yaml:"condition_config,omitempty"`
	CreatedAt          null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	DeletedAt          null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *actionEffectR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L actionEffectL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ActionEffectColumns = struct {
	ID                 string
	ActionID           string
	EffectID           string
	ExecutionOrder     string
	ParameterOverrides string
	IsConditional      string
	ConditionConfig    string
	CreatedAt          string
	DeletedAt          string
}{
	ID:                 "id",
	ActionID:           "action_id",
	EffectID:           "effect_id",
	ExecutionOrder:     "execution_order",
	ParameterOverrides: "parameter_overrides",
	IsConditional:      "is_conditional",
	ConditionConfig:    "condition_config",
	CreatedAt:          "created_at",
	DeletedAt:          "deleted_at",
}

var ActionEffectTableColumns = struct {
	ID                 string
	ActionID           string
	EffectID           string
	ExecutionOrder     string
	ParameterOverrides string
	IsConditional      string
	ConditionConfig    string
	CreatedAt          string
	DeletedAt          string
}{
	ID:                 "action_effects.id",
	ActionID:           "action_effects.action_id",
	EffectID:           "action_effects.effect_id",
	ExecutionOrder:     "action_effects.execution_order",
	ParameterOverrides: "action_effects.parameter_overrides",
	IsConditional:      "action_effects.is_conditional",
	ConditionConfig:    "action_effects.condition_config",
	CreatedAt:          "action_effects.created_at",
	DeletedAt:          "action_effects.deleted_at",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ActionEffectWhere = struct {
	ID                 whereHelperstring
	ActionID           whereHelperstring
	EffectID           whereHelperstring
	ExecutionOrder     whereHelpernull_Int
	ParameterOverrides whereHelpernull_JSON
	IsConditional      whereHelpernull_Bool
	ConditionConfig    whereHelpernull_JSON
	CreatedAt          whereHelpernull_Time
	DeletedAt          whereHelpernull_Time
}{
	ID:                 whereHelperstring{field: "\"action_effects\".\"id\""},
	ActionID:           whereHelperstring{field: "\"action_effects\".\"action_id\""},
	EffectID:           whereHelperstring{field: "\"action_effects\".\"effect_id\""},
	ExecutionOrder:     whereHelpernull_Int{field: "\"action_effects\".\"execution_order\""},
	ParameterOverrides: whereHelpernull_JSON{field: "\"action_effects\".\"parameter_overrides\""},
	IsConditional:      whereHelpernull_Bool{field: "\"action_effects\".\"is_conditional\""},
	ConditionConfig:    whereHelpernull_JSON{field: "\"action_effects\".\"condition_config\""},
	CreatedAt:          whereHelpernull_Time{field: "\"action_effects\".\"created_at\""},
	DeletedAt:          whereHelpernull_Time{field: "\"action_effects\".\"deleted_at\""},
}

// ActionEffectRels is where relationship names are stored.
var ActionEffectRels = struct {
	Action string
	Effect string
}{
	Action: "Action",
	Effect: "Effect",
}

// actionEffectR is where relationships are stored.
type actionEffectR struct {
	Action *Action `boil:"Action" json:"Action" toml:"Action" yaml:"Action"`
	Effect *Effect `boil:"Effect" json:"Effect" toml:"Effect" yaml:"Effect"`
}

// NewStruct creates a new relationship struct
func (*actionEffectR) NewStruct() *actionEffectR {
	return &actionEffectR{}
}

func (o *ActionEffect) GetAction() *Action {
	if o == nil {
		return nil
	}

	return o.R.GetAction()
}

func (r *actionEffectR) GetAction() *Action {
	if r == nil {
		return nil
	}

	return r.Action
}

func (o *ActionEffect) GetEffect() *Effect {
	if o == nil {
		return nil
	}

	return o.R.GetEffect()
}

func (r *actionEffectR) GetEffect() *Effect {
	if r == nil {
		return nil
	}

	return r.Effect
}

// actionEffectL is where Load methods for each relationship are stored.
type actionEffectL struct{}

var (
	actionEffectAllColumns            = []string{"id", "action_id", "effect_id", "execution_order", "parameter_overrides", "is_conditional", "condition_config", "created_at", "deleted_at"}
	actionEffectColumnsWithoutDefault = []string{"action_id", "effect_id"}
	actionEffectColumnsWithDefault    = []string{"id", "execution_order", "parameter_overrides", "is_conditional", "condition_config", "created_at", "deleted_at"}
	actionEffectPrimaryKeyColumns     = []string{"id"}
	actionEffectGeneratedColumns      = []string{}
)

type (
	// ActionEffectSlice is an alias for a slice of pointers to ActionEffect.
	// This should almost always be used instead of []ActionEffect.
	ActionEffectSlice []*ActionEffect
	// ActionEffectHook is the signature for custom ActionEffect hook methods
	ActionEffectHook func(context.Context, boil.ContextExecutor, *ActionEffect) error

	actionEffectQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	actionEffectType                 = reflect.TypeOf(&ActionEffect{})
	actionEffectMapping              = queries.MakeStructMapping(actionEffectType)
	actionEffectPrimaryKeyMapping, _ = queries.BindMapping(actionEffectType, actionEffectMapping, actionEffectPrimaryKeyColumns)
	actionEffectInsertCacheMut       sync.RWMutex
	actionEffectInsertCache          = make(map[string]insertCache)
	actionEffectUpdateCacheMut       sync.RWMutex
	actionEffectUpdateCache          = make(map[string]updateCache)
	actionEffectUpsertCacheMut       sync.RWMutex
	actionEffectUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var actionEffectAfterSelectMu sync.Mutex
var actionEffectAfterSelectHooks []ActionEffectHook

var actionEffectBeforeInsertMu sync.Mutex
var actionEffectBeforeInsertHooks []ActionEffectHook
var actionEffectAfterInsertMu sync.Mutex
var actionEffectAfterInsertHooks []ActionEffectHook

var actionEffectBeforeUpdateMu sync.Mutex
var actionEffectBeforeUpdateHooks []ActionEffectHook
var actionEffectAfterUpdateMu sync.Mutex
var actionEffectAfterUpdateHooks []ActionEffectHook

var actionEffectBeforeDeleteMu sync.Mutex
var actionEffectBeforeDeleteHooks []ActionEffectHook
var actionEffectAfterDeleteMu sync.Mutex
var actionEffectAfterDeleteHooks []ActionEffectHook

var actionEffectBeforeUpsertMu sync.Mutex
var actionEffectBeforeUpsertHooks []ActionEffectHook
var actionEffectAfterUpsertMu sync.Mutex
var actionEffectAfterUpsertHooks []ActionEffectHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ActionEffect) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ActionEffect) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ActionEffect) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ActionEffect) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ActionEffect) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ActionEffect) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ActionEffect) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ActionEffect) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ActionEffect) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range actionEffectAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddActionEffectHook registers your hook function for all future operations.
func AddActionEffectHook(hookPoint boil.HookPoint, actionEffectHook ActionEffectHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		actionEffectAfterSelectMu.Lock()
		actionEffectAfterSelectHooks = append(actionEffectAfterSelectHooks, actionEffectHook)
		actionEffectAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		actionEffectBeforeInsertMu.Lock()
		actionEffectBeforeInsertHooks = append(actionEffectBeforeInsertHooks, actionEffectHook)
		actionEffectBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		actionEffectAfterInsertMu.Lock()
		actionEffectAfterInsertHooks = append(actionEffectAfterInsertHooks, actionEffectHook)
		actionEffectAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		actionEffectBeforeUpdateMu.Lock()
		actionEffectBeforeUpdateHooks = append(actionEffectBeforeUpdateHooks, actionEffectHook)
		actionEffectBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		actionEffectAfterUpdateMu.Lock()
		actionEffectAfterUpdateHooks = append(actionEffectAfterUpdateHooks, actionEffectHook)
		actionEffectAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		actionEffectBeforeDeleteMu.Lock()
		actionEffectBeforeDeleteHooks = append(actionEffectBeforeDeleteHooks, actionEffectHook)
		actionEffectBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		actionEffectAfterDeleteMu.Lock()
		actionEffectAfterDeleteHooks = append(actionEffectAfterDeleteHooks, actionEffectHook)
		actionEffectAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		actionEffectBeforeUpsertMu.Lock()
		actionEffectBeforeUpsertHooks = append(actionEffectBeforeUpsertHooks, actionEffectHook)
		actionEffectBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		actionEffectAfterUpsertMu.Lock()
		actionEffectAfterUpsertHooks = append(actionEffectAfterUpsertHooks, actionEffectHook)
		actionEffectAfterUpsertMu.Unlock()
	}
}

// OneG returns a single actionEffect record from the query using the global executor.
func (q actionEffectQuery) OneG(ctx context.Context) (*ActionEffect, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single actionEffect record from the query using the global executor, and panics on error.
func (q actionEffectQuery) OneGP(ctx context.Context) *ActionEffect {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single actionEffect record from the query, and panics on error.
func (q actionEffectQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *ActionEffect {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single actionEffect record from the query.
func (q actionEffectQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ActionEffect, error) {
	o := &ActionEffect{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for action_effects")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all ActionEffect records from the query using the global executor.
func (q actionEffectQuery) AllG(ctx context.Context) (ActionEffectSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all ActionEffect records from the query using the global executor, and panics on error.
func (q actionEffectQuery) AllGP(ctx context.Context) ActionEffectSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all ActionEffect records from the query, and panics on error.
func (q actionEffectQuery) AllP(ctx context.Context, exec boil.ContextExecutor) ActionEffectSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all ActionEffect records from the query.
func (q actionEffectQuery) All(ctx context.Context, exec boil.ContextExecutor) (ActionEffectSlice, error) {
	var o []*ActionEffect

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to ActionEffect slice")
	}

	if len(actionEffectAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all ActionEffect records in the query using the global executor
func (q actionEffectQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all ActionEffect records in the query using the global executor, and panics on error.
func (q actionEffectQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all ActionEffect records in the query, and panics on error.
func (q actionEffectQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all ActionEffect records in the query.
func (q actionEffectQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count action_effects rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q actionEffectQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q actionEffectQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q actionEffectQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q actionEffectQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if action_effects exists")
	}

	return count > 0, nil
}

// Action pointed to by the foreign key.
func (o *ActionEffect) Action(mods ...qm.QueryMod) actionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ActionID),
	}

	queryMods = append(queryMods, mods...)

	return Actions(queryMods...)
}

// Effect pointed to by the foreign key.
func (o *ActionEffect) Effect(mods ...qm.QueryMod) effectQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.EffectID),
	}

	queryMods = append(queryMods, mods...)

	return Effects(queryMods...)
}

// LoadAction allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (actionEffectL) LoadAction(ctx context.Context, e boil.ContextExecutor, singular bool, maybeActionEffect interface{}, mods queries.Applicator) error {
	var slice []*ActionEffect
	var object *ActionEffect

	if singular {
		var ok bool
		object, ok = maybeActionEffect.(*ActionEffect)
		if !ok {
			object = new(ActionEffect)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeActionEffect)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeActionEffect))
			}
		}
	} else {
		s, ok := maybeActionEffect.(*[]*ActionEffect)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeActionEffect)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeActionEffect))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &actionEffectR{}
		}
		args[object.ActionID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &actionEffectR{}
			}

			args[obj.ActionID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`actions`),
		qm.WhereIn(`actions.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`actions.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Action")
	}

	var resultSlice []*Action
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Action")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for actions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for actions")
	}

	if len(actionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Action = foreign
		if foreign.R == nil {
			foreign.R = &actionR{}
		}
		foreign.R.ActionEffects = append(foreign.R.ActionEffects, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ActionID == foreign.ID {
				local.R.Action = foreign
				if foreign.R == nil {
					foreign.R = &actionR{}
				}
				foreign.R.ActionEffects = append(foreign.R.ActionEffects, local)
				break
			}
		}
	}

	return nil
}

// LoadEffect allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (actionEffectL) LoadEffect(ctx context.Context, e boil.ContextExecutor, singular bool, maybeActionEffect interface{}, mods queries.Applicator) error {
	var slice []*ActionEffect
	var object *ActionEffect

	if singular {
		var ok bool
		object, ok = maybeActionEffect.(*ActionEffect)
		if !ok {
			object = new(ActionEffect)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeActionEffect)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeActionEffect))
			}
		}
	} else {
		s, ok := maybeActionEffect.(*[]*ActionEffect)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeActionEffect)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeActionEffect))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &actionEffectR{}
		}
		args[object.EffectID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &actionEffectR{}
			}

			args[obj.EffectID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`effects`),
		qm.WhereIn(`effects.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`effects.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Effect")
	}

	var resultSlice []*Effect
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Effect")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for effects")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for effects")
	}

	if len(effectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Effect = foreign
		if foreign.R == nil {
			foreign.R = &effectR{}
		}
		foreign.R.ActionEffects = append(foreign.R.ActionEffects, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EffectID == foreign.ID {
				local.R.Effect = foreign
				if foreign.R == nil {
					foreign.R = &effectR{}
				}
				foreign.R.ActionEffects = append(foreign.R.ActionEffects, local)
				break
			}
		}
	}

	return nil
}

// SetActionG of the actionEffect to the related item.
// Sets o.R.Action to related.
// Adds o to related.R.ActionEffects.
// Uses the global database handle.
func (o *ActionEffect) SetActionG(ctx context.Context, insert bool, related *Action) error {
	return o.SetAction(ctx, boil.GetContextDB(), insert, related)
}

// SetActionP of the actionEffect to the related item.
// Sets o.R.Action to related.
// Adds o to related.R.ActionEffects.
// Panics on error.
func (o *ActionEffect) SetActionP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Action) {
	if err := o.SetAction(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetActionGP of the actionEffect to the related item.
// Sets o.R.Action to related.
// Adds o to related.R.ActionEffects.
// Uses the global database handle and panics on error.
func (o *ActionEffect) SetActionGP(ctx context.Context, insert bool, related *Action) {
	if err := o.SetAction(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAction of the actionEffect to the related item.
// Sets o.R.Action to related.
// Adds o to related.R.ActionEffects.
func (o *ActionEffect) SetAction(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Action) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"action_effects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"action_id"}),
		strmangle.WhereClause("\"", "\"", 2, actionEffectPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ActionID = related.ID
	if o.R == nil {
		o.R = &actionEffectR{
			Action: related,
		}
	} else {
		o.R.Action = related
	}

	if related.R == nil {
		related.R = &actionR{
			ActionEffects: ActionEffectSlice{o},
		}
	} else {
		related.R.ActionEffects = append(related.R.ActionEffects, o)
	}

	return nil
}

// SetEffectG of the actionEffect to the related item.
// Sets o.R.Effect to related.
// Adds o to related.R.ActionEffects.
// Uses the global database handle.
func (o *ActionEffect) SetEffectG(ctx context.Context, insert bool, related *Effect) error {
	return o.SetEffect(ctx, boil.GetContextDB(), insert, related)
}

// SetEffectP of the actionEffect to the related item.
// Sets o.R.Effect to related.
// Adds o to related.R.ActionEffects.
// Panics on error.
func (o *ActionEffect) SetEffectP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Effect) {
	if err := o.SetEffect(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEffectGP of the actionEffect to the related item.
// Sets o.R.Effect to related.
// Adds o to related.R.ActionEffects.
// Uses the global database handle and panics on error.
func (o *ActionEffect) SetEffectGP(ctx context.Context, insert bool, related *Effect) {
	if err := o.SetEffect(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEffect of the actionEffect to the related item.
// Sets o.R.Effect to related.
// Adds o to related.R.ActionEffects.
func (o *ActionEffect) SetEffect(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Effect) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"action_effects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"effect_id"}),
		strmangle.WhereClause("\"", "\"", 2, actionEffectPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EffectID = related.ID
	if o.R == nil {
		o.R = &actionEffectR{
			Effect: related,
		}
	} else {
		o.R.Effect = related
	}

	if related.R == nil {
		related.R = &effectR{
			ActionEffects: ActionEffectSlice{o},
		}
	} else {
		related.R.ActionEffects = append(related.R.ActionEffects, o)
	}

	return nil
}

// ActionEffects retrieves all the records using an executor.
func ActionEffects(mods ...qm.QueryMod) actionEffectQuery {
	mods = append(mods, qm.From("\"action_effects\""), qmhelper.WhereIsNull("\"action_effects\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"action_effects\".*"})
	}

	return actionEffectQuery{q}
}

// FindActionEffectG retrieves a single record by ID.
func FindActionEffectG(ctx context.Context, iD string, selectCols ...string) (*ActionEffect, error) {
	return FindActionEffect(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindActionEffectP retrieves a single record by ID with an executor, and panics on error.
func FindActionEffectP(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) *ActionEffect {
	retobj, err := FindActionEffect(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindActionEffectGP retrieves a single record by ID, and panics on error.
func FindActionEffectGP(ctx context.Context, iD string, selectCols ...string) *ActionEffect {
	retobj, err := FindActionEffect(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindActionEffect retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindActionEffect(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ActionEffect, error) {
	actionEffectObj := &ActionEffect{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"action_effects\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, actionEffectObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from action_effects")
	}

	if err = actionEffectObj.doAfterSelectHooks(ctx, exec); err != nil {
		return actionEffectObj, err
	}

	return actionEffectObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ActionEffect) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *ActionEffect) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *ActionEffect) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ActionEffect) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no action_effects provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(actionEffectColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	actionEffectInsertCacheMut.RLock()
	cache, cached := actionEffectInsertCache[key]
	actionEffectInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			actionEffectAllColumns,
			actionEffectColumnsWithDefault,
			actionEffectColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(actionEffectType, actionEffectMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(actionEffectType, actionEffectMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"action_effects\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"action_effects\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into action_effects")
	}

	if !cached {
		actionEffectInsertCacheMut.Lock()
		actionEffectInsertCache[key] = cache
		actionEffectInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single ActionEffect record using the global executor.
// See Update for more documentation.
func (o *ActionEffect) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the ActionEffect, and panics on error.
// See Update for more documentation.
func (o *ActionEffect) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single ActionEffect record using the global executor. Panics on error.
// See Update for more documentation.
func (o *ActionEffect) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the ActionEffect.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ActionEffect) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	actionEffectUpdateCacheMut.RLock()
	cache, cached := actionEffectUpdateCache[key]
	actionEffectUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			actionEffectAllColumns,
			actionEffectPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update action_effects, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"action_effects\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, actionEffectPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(actionEffectType, actionEffectMapping, append(wl, actionEffectPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update action_effects row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for action_effects")
	}

	if !cached {
		actionEffectUpdateCacheMut.Lock()
		actionEffectUpdateCache[key] = cache
		actionEffectUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q actionEffectQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q actionEffectQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q actionEffectQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q actionEffectQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for action_effects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for action_effects")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ActionEffectSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o ActionEffectSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o ActionEffectSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ActionEffectSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), actionEffectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"action_effects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, actionEffectPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in actionEffect slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all actionEffect")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ActionEffect) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *ActionEffect) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *ActionEffect) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ActionEffect) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no action_effects provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(actionEffectColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	actionEffectUpsertCacheMut.RLock()
	cache, cached := actionEffectUpsertCache[key]
	actionEffectUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			actionEffectAllColumns,
			actionEffectColumnsWithDefault,
			actionEffectColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			actionEffectAllColumns,
			actionEffectPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert action_effects, could not build update column list")
		}

		ret := strmangle.SetComplement(actionEffectAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(actionEffectPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert action_effects, could not build conflict column list")
			}

			conflict = make([]string, len(actionEffectPrimaryKeyColumns))
			copy(conflict, actionEffectPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"action_effects\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(actionEffectType, actionEffectMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(actionEffectType, actionEffectMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert action_effects")
	}

	if !cached {
		actionEffectUpsertCacheMut.Lock()
		actionEffectUpsertCache[key] = cache
		actionEffectUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single ActionEffect record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ActionEffect) DeleteG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteP deletes a single ActionEffect record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *ActionEffect) DeleteP(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) int64 {
	rowsAff, err := o.Delete(ctx, exec, hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single ActionEffect record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *ActionEffect) DeleteGP(ctx context.Context, hardDelete bool) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB(), hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single ActionEffect record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ActionEffect) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no ActionEffect provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), actionEffectPrimaryKeyMapping)
		sql = "DELETE FROM \"action_effects\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"action_effects\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(actionEffectType, actionEffectMapping, append(wl, actionEffectPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from action_effects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for action_effects")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q actionEffectQuery) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAllP deletes all rows, and panics on error.
func (q actionEffectQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec, hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q actionEffectQuery) DeleteAllGP(ctx context.Context, hardDelete bool) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q actionEffectQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no actionEffectQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from action_effects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for action_effects")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ActionEffectSlice) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o ActionEffectSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec, hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o ActionEffectSlice) DeleteAllGP(ctx context.Context, hardDelete bool) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ActionEffectSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(actionEffectBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), actionEffectPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"action_effects\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, actionEffectPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), actionEffectPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"action_effects\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, actionEffectPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from actionEffect slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for action_effects")
	}

	if len(actionEffectAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ActionEffect) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("entity: no ActionEffect provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *ActionEffect) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *ActionEffect) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ActionEffect) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindActionEffect(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ActionEffectSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("entity: empty ActionEffectSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ActionEffectSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ActionEffectSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ActionEffectSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ActionEffectSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), actionEffectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"action_effects\".* FROM \"action_effects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, actionEffectPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in ActionEffectSlice")
	}

	*o = slice

	return nil
}

// ActionEffectExistsG checks if the ActionEffect row exists.
func ActionEffectExistsG(ctx context.Context, iD string) (bool, error) {
	return ActionEffectExists(ctx, boil.GetContextDB(), iD)
}

// ActionEffectExistsP checks if the ActionEffect row exists. Panics on error.
func ActionEffectExistsP(ctx context.Context, exec boil.ContextExecutor, iD string) bool {
	e, err := ActionEffectExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ActionEffectExistsGP checks if the ActionEffect row exists. Panics on error.
func ActionEffectExistsGP(ctx context.Context, iD string) bool {
	e, err := ActionEffectExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ActionEffectExists checks if the ActionEffect row exists.
func ActionEffectExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"action_effects\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if action_effects exists")
	}

	return exists, nil
}

// Exists checks if the ActionEffect row exists.
func (o *ActionEffect) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ActionEffectExists(ctx, exec, o.ID)
}
