// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var ViewNames = struct {
	ActionEffectsDetail  string
	BuffEffectsDetail    string
	SkillActionRelations string
}{
	ActionEffectsDetail:  "action_effects_detail",
	BuffEffectsDetail:    "buff_effects_detail",
	SkillActionRelations: "skill_action_relations",
}
