// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ClassTagRelation is an object representing the database table.
type ClassTagRelation struct {
	ID        string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ClassID   string    `boil:"class_id" json:"class_id" toml:"class_id" yaml:"class_id"`
	TagID     string    `boil:"tag_id" json:"tag_id" toml:"tag_id" yaml:"tag_id"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *classTagRelationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L classTagRelationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ClassTagRelationColumns = struct {
	ID        string
	ClassID   string
	TagID     string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	ClassID:   "class_id",
	TagID:     "tag_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var ClassTagRelationTableColumns = struct {
	ID        string
	ClassID   string
	TagID     string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "class_tag_relations.id",
	ClassID:   "class_tag_relations.class_id",
	TagID:     "class_tag_relations.tag_id",
	CreatedAt: "class_tag_relations.created_at",
	UpdatedAt: "class_tag_relations.updated_at",
}

// Generated where

var ClassTagRelationWhere = struct {
	ID        whereHelperstring
	ClassID   whereHelperstring
	TagID     whereHelperstring
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperstring{field: "\"class_tag_relations\".\"id\""},
	ClassID:   whereHelperstring{field: "\"class_tag_relations\".\"class_id\""},
	TagID:     whereHelperstring{field: "\"class_tag_relations\".\"tag_id\""},
	CreatedAt: whereHelpernull_Time{field: "\"class_tag_relations\".\"created_at\""},
	UpdatedAt: whereHelpernull_Time{field: "\"class_tag_relations\".\"updated_at\""},
}

// ClassTagRelationRels is where relationship names are stored.
var ClassTagRelationRels = struct {
	Class string
	Tag   string
}{
	Class: "Class",
	Tag:   "Tag",
}

// classTagRelationR is where relationships are stored.
type classTagRelationR struct {
	Class *Class `boil:"Class" json:"Class" toml:"Class" yaml:"Class"`
	Tag   *Tag   `boil:"Tag" json:"Tag" toml:"Tag" yaml:"Tag"`
}

// NewStruct creates a new relationship struct
func (*classTagRelationR) NewStruct() *classTagRelationR {
	return &classTagRelationR{}
}

func (o *ClassTagRelation) GetClass() *Class {
	if o == nil {
		return nil
	}

	return o.R.GetClass()
}

func (r *classTagRelationR) GetClass() *Class {
	if r == nil {
		return nil
	}

	return r.Class
}

func (o *ClassTagRelation) GetTag() *Tag {
	if o == nil {
		return nil
	}

	return o.R.GetTag()
}

func (r *classTagRelationR) GetTag() *Tag {
	if r == nil {
		return nil
	}

	return r.Tag
}

// classTagRelationL is where Load methods for each relationship are stored.
type classTagRelationL struct{}

var (
	classTagRelationAllColumns            = []string{"id", "class_id", "tag_id", "created_at", "updated_at"}
	classTagRelationColumnsWithoutDefault = []string{"class_id", "tag_id"}
	classTagRelationColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	classTagRelationPrimaryKeyColumns     = []string{"id"}
	classTagRelationGeneratedColumns      = []string{}
)

type (
	// ClassTagRelationSlice is an alias for a slice of pointers to ClassTagRelation.
	// This should almost always be used instead of []ClassTagRelation.
	ClassTagRelationSlice []*ClassTagRelation
	// ClassTagRelationHook is the signature for custom ClassTagRelation hook methods
	ClassTagRelationHook func(context.Context, boil.ContextExecutor, *ClassTagRelation) error

	classTagRelationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	classTagRelationType                 = reflect.TypeOf(&ClassTagRelation{})
	classTagRelationMapping              = queries.MakeStructMapping(classTagRelationType)
	classTagRelationPrimaryKeyMapping, _ = queries.BindMapping(classTagRelationType, classTagRelationMapping, classTagRelationPrimaryKeyColumns)
	classTagRelationInsertCacheMut       sync.RWMutex
	classTagRelationInsertCache          = make(map[string]insertCache)
	classTagRelationUpdateCacheMut       sync.RWMutex
	classTagRelationUpdateCache          = make(map[string]updateCache)
	classTagRelationUpsertCacheMut       sync.RWMutex
	classTagRelationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var classTagRelationAfterSelectMu sync.Mutex
var classTagRelationAfterSelectHooks []ClassTagRelationHook

var classTagRelationBeforeInsertMu sync.Mutex
var classTagRelationBeforeInsertHooks []ClassTagRelationHook
var classTagRelationAfterInsertMu sync.Mutex
var classTagRelationAfterInsertHooks []ClassTagRelationHook

var classTagRelationBeforeUpdateMu sync.Mutex
var classTagRelationBeforeUpdateHooks []ClassTagRelationHook
var classTagRelationAfterUpdateMu sync.Mutex
var classTagRelationAfterUpdateHooks []ClassTagRelationHook

var classTagRelationBeforeDeleteMu sync.Mutex
var classTagRelationBeforeDeleteHooks []ClassTagRelationHook
var classTagRelationAfterDeleteMu sync.Mutex
var classTagRelationAfterDeleteHooks []ClassTagRelationHook

var classTagRelationBeforeUpsertMu sync.Mutex
var classTagRelationBeforeUpsertHooks []ClassTagRelationHook
var classTagRelationAfterUpsertMu sync.Mutex
var classTagRelationAfterUpsertHooks []ClassTagRelationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ClassTagRelation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ClassTagRelation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ClassTagRelation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ClassTagRelation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ClassTagRelation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ClassTagRelation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ClassTagRelation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ClassTagRelation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ClassTagRelation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classTagRelationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddClassTagRelationHook registers your hook function for all future operations.
func AddClassTagRelationHook(hookPoint boil.HookPoint, classTagRelationHook ClassTagRelationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		classTagRelationAfterSelectMu.Lock()
		classTagRelationAfterSelectHooks = append(classTagRelationAfterSelectHooks, classTagRelationHook)
		classTagRelationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		classTagRelationBeforeInsertMu.Lock()
		classTagRelationBeforeInsertHooks = append(classTagRelationBeforeInsertHooks, classTagRelationHook)
		classTagRelationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		classTagRelationAfterInsertMu.Lock()
		classTagRelationAfterInsertHooks = append(classTagRelationAfterInsertHooks, classTagRelationHook)
		classTagRelationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		classTagRelationBeforeUpdateMu.Lock()
		classTagRelationBeforeUpdateHooks = append(classTagRelationBeforeUpdateHooks, classTagRelationHook)
		classTagRelationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		classTagRelationAfterUpdateMu.Lock()
		classTagRelationAfterUpdateHooks = append(classTagRelationAfterUpdateHooks, classTagRelationHook)
		classTagRelationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		classTagRelationBeforeDeleteMu.Lock()
		classTagRelationBeforeDeleteHooks = append(classTagRelationBeforeDeleteHooks, classTagRelationHook)
		classTagRelationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		classTagRelationAfterDeleteMu.Lock()
		classTagRelationAfterDeleteHooks = append(classTagRelationAfterDeleteHooks, classTagRelationHook)
		classTagRelationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		classTagRelationBeforeUpsertMu.Lock()
		classTagRelationBeforeUpsertHooks = append(classTagRelationBeforeUpsertHooks, classTagRelationHook)
		classTagRelationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		classTagRelationAfterUpsertMu.Lock()
		classTagRelationAfterUpsertHooks = append(classTagRelationAfterUpsertHooks, classTagRelationHook)
		classTagRelationAfterUpsertMu.Unlock()
	}
}

// One returns a single classTagRelation record from the query.
func (q classTagRelationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ClassTagRelation, error) {
	o := &ClassTagRelation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for class_tag_relations")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ClassTagRelation records from the query.
func (q classTagRelationQuery) All(ctx context.Context, exec boil.ContextExecutor) (ClassTagRelationSlice, error) {
	var o []*ClassTagRelation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to ClassTagRelation slice")
	}

	if len(classTagRelationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ClassTagRelation records in the query.
func (q classTagRelationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count class_tag_relations rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q classTagRelationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if class_tag_relations exists")
	}

	return count > 0, nil
}

// Class pointed to by the foreign key.
func (o *ClassTagRelation) Class(mods ...qm.QueryMod) classQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ClassID),
	}

	queryMods = append(queryMods, mods...)

	return Classes(queryMods...)
}

// Tag pointed to by the foreign key.
func (o *ClassTagRelation) Tag(mods ...qm.QueryMod) tagQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TagID),
	}

	queryMods = append(queryMods, mods...)

	return Tags(queryMods...)
}

// LoadClass allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (classTagRelationL) LoadClass(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClassTagRelation interface{}, mods queries.Applicator) error {
	var slice []*ClassTagRelation
	var object *ClassTagRelation

	if singular {
		var ok bool
		object, ok = maybeClassTagRelation.(*ClassTagRelation)
		if !ok {
			object = new(ClassTagRelation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClassTagRelation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClassTagRelation))
			}
		}
	} else {
		s, ok := maybeClassTagRelation.(*[]*ClassTagRelation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClassTagRelation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClassTagRelation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &classTagRelationR{}
		}
		args[object.ClassID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classTagRelationR{}
			}

			args[obj.ClassID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`classes`),
		qm.WhereIn(`classes.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Class")
	}

	var resultSlice []*Class
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Class")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for classes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for classes")
	}

	if len(classAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Class = foreign
		if foreign.R == nil {
			foreign.R = &classR{}
		}
		foreign.R.ClassTagRelations = append(foreign.R.ClassTagRelations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ClassID == foreign.ID {
				local.R.Class = foreign
				if foreign.R == nil {
					foreign.R = &classR{}
				}
				foreign.R.ClassTagRelations = append(foreign.R.ClassTagRelations, local)
				break
			}
		}
	}

	return nil
}

// LoadTag allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (classTagRelationL) LoadTag(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClassTagRelation interface{}, mods queries.Applicator) error {
	var slice []*ClassTagRelation
	var object *ClassTagRelation

	if singular {
		var ok bool
		object, ok = maybeClassTagRelation.(*ClassTagRelation)
		if !ok {
			object = new(ClassTagRelation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClassTagRelation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClassTagRelation))
			}
		}
	} else {
		s, ok := maybeClassTagRelation.(*[]*ClassTagRelation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClassTagRelation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClassTagRelation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &classTagRelationR{}
		}
		args[object.TagID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classTagRelationR{}
			}

			args[obj.TagID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tags`),
		qm.WhereIn(`tags.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tag")
	}

	var resultSlice []*Tag
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tag")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tags")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tags")
	}

	if len(tagAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tag = foreign
		if foreign.R == nil {
			foreign.R = &tagR{}
		}
		foreign.R.ClassTagRelations = append(foreign.R.ClassTagRelations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TagID == foreign.ID {
				local.R.Tag = foreign
				if foreign.R == nil {
					foreign.R = &tagR{}
				}
				foreign.R.ClassTagRelations = append(foreign.R.ClassTagRelations, local)
				break
			}
		}
	}

	return nil
}

// SetClass of the classTagRelation to the related item.
// Sets o.R.Class to related.
// Adds o to related.R.ClassTagRelations.
func (o *ClassTagRelation) SetClass(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Class) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"class_tag_relations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"class_id"}),
		strmangle.WhereClause("\"", "\"", 2, classTagRelationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ClassID = related.ID
	if o.R == nil {
		o.R = &classTagRelationR{
			Class: related,
		}
	} else {
		o.R.Class = related
	}

	if related.R == nil {
		related.R = &classR{
			ClassTagRelations: ClassTagRelationSlice{o},
		}
	} else {
		related.R.ClassTagRelations = append(related.R.ClassTagRelations, o)
	}

	return nil
}

// SetTag of the classTagRelation to the related item.
// Sets o.R.Tag to related.
// Adds o to related.R.ClassTagRelations.
func (o *ClassTagRelation) SetTag(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tag) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"class_tag_relations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tag_id"}),
		strmangle.WhereClause("\"", "\"", 2, classTagRelationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TagID = related.ID
	if o.R == nil {
		o.R = &classTagRelationR{
			Tag: related,
		}
	} else {
		o.R.Tag = related
	}

	if related.R == nil {
		related.R = &tagR{
			ClassTagRelations: ClassTagRelationSlice{o},
		}
	} else {
		related.R.ClassTagRelations = append(related.R.ClassTagRelations, o)
	}

	return nil
}

// ClassTagRelations retrieves all the records using an executor.
func ClassTagRelations(mods ...qm.QueryMod) classTagRelationQuery {
	mods = append(mods, qm.From("\"class_tag_relations\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"class_tag_relations\".*"})
	}

	return classTagRelationQuery{q}
}

// FindClassTagRelation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindClassTagRelation(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ClassTagRelation, error) {
	classTagRelationObj := &ClassTagRelation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"class_tag_relations\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, classTagRelationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from class_tag_relations")
	}

	if err = classTagRelationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return classTagRelationObj, err
	}

	return classTagRelationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ClassTagRelation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no class_tag_relations provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(classTagRelationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	classTagRelationInsertCacheMut.RLock()
	cache, cached := classTagRelationInsertCache[key]
	classTagRelationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			classTagRelationAllColumns,
			classTagRelationColumnsWithDefault,
			classTagRelationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(classTagRelationType, classTagRelationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(classTagRelationType, classTagRelationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"class_tag_relations\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"class_tag_relations\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into class_tag_relations")
	}

	if !cached {
		classTagRelationInsertCacheMut.Lock()
		classTagRelationInsertCache[key] = cache
		classTagRelationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ClassTagRelation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ClassTagRelation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	classTagRelationUpdateCacheMut.RLock()
	cache, cached := classTagRelationUpdateCache[key]
	classTagRelationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			classTagRelationAllColumns,
			classTagRelationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update class_tag_relations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"class_tag_relations\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, classTagRelationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(classTagRelationType, classTagRelationMapping, append(wl, classTagRelationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update class_tag_relations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for class_tag_relations")
	}

	if !cached {
		classTagRelationUpdateCacheMut.Lock()
		classTagRelationUpdateCache[key] = cache
		classTagRelationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q classTagRelationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for class_tag_relations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for class_tag_relations")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ClassTagRelationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classTagRelationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"class_tag_relations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, classTagRelationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in classTagRelation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all classTagRelation")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ClassTagRelation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no class_tag_relations provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(classTagRelationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	classTagRelationUpsertCacheMut.RLock()
	cache, cached := classTagRelationUpsertCache[key]
	classTagRelationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			classTagRelationAllColumns,
			classTagRelationColumnsWithDefault,
			classTagRelationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			classTagRelationAllColumns,
			classTagRelationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert class_tag_relations, could not build update column list")
		}

		ret := strmangle.SetComplement(classTagRelationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(classTagRelationPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert class_tag_relations, could not build conflict column list")
			}

			conflict = make([]string, len(classTagRelationPrimaryKeyColumns))
			copy(conflict, classTagRelationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"class_tag_relations\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(classTagRelationType, classTagRelationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(classTagRelationType, classTagRelationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert class_tag_relations")
	}

	if !cached {
		classTagRelationUpsertCacheMut.Lock()
		classTagRelationUpsertCache[key] = cache
		classTagRelationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ClassTagRelation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ClassTagRelation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no ClassTagRelation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), classTagRelationPrimaryKeyMapping)
	sql := "DELETE FROM \"class_tag_relations\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from class_tag_relations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for class_tag_relations")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q classTagRelationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no classTagRelationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from class_tag_relations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for class_tag_relations")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ClassTagRelationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(classTagRelationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classTagRelationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"class_tag_relations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, classTagRelationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from classTagRelation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for class_tag_relations")
	}

	if len(classTagRelationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ClassTagRelation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindClassTagRelation(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ClassTagRelationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ClassTagRelationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classTagRelationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"class_tag_relations\".* FROM \"class_tag_relations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, classTagRelationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in ClassTagRelationSlice")
	}

	*o = slice

	return nil
}

// ClassTagRelationExists checks if the ClassTagRelation row exists.
func ClassTagRelationExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"class_tag_relations\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if class_tag_relations exists")
	}

	return exists, nil
}

// Exists checks if the ClassTagRelation row exists.
func (o *ClassTagRelation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ClassTagRelationExists(ctx, exec, o.ID)
}
