// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Class is an object representing the database table.
type Class struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ClassCode      string      `boil:"class_code" json:"class_code" toml:"class_code" yaml:"class_code"`
	ClassName      string      `boil:"class_name" json:"class_name" toml:"class_name" yaml:"class_name"`
	Description    null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	LoreText       null.String `boil:"lore_text" json:"lore_text,omitempty" toml:"lore_text" yaml:"lore_text,omitempty"`
	Tier           string      `boil:"tier" json:"tier" toml:"tier" yaml:"tier"`
	PromotionCount null.Int16  `boil:"promotion_count" json:"promotion_count,omitempty" toml:"promotion_count" yaml:"promotion_count,omitempty"`
	Icon           null.String `boil:"icon" json:"icon,omitempty" toml:"icon" yaml:"icon,omitempty"`
	Color          null.String `boil:"color" json:"color,omitempty" toml:"color" yaml:"color,omitempty"`
	IsActive       null.Bool   `boil:"is_active" json:"is_active,omitempty" toml:"is_active" yaml:"is_active,omitempty"`
	IsVisible      null.Bool   `boil:"is_visible" json:"is_visible,omitempty" toml:"is_visible" yaml:"is_visible,omitempty"`
	DisplayOrder   null.Int16  `boil:"display_order" json:"display_order,omitempty" toml:"display_order" yaml:"display_order,omitempty"`
	CreatedAt      null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt      null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt      null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *classR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L classL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ClassColumns = struct {
	ID             string
	ClassCode      string
	ClassName      string
	Description    string
	LoreText       string
	Tier           string
	PromotionCount string
	Icon           string
	Color          string
	IsActive       string
	IsVisible      string
	DisplayOrder   string
	CreatedAt      string
	UpdatedAt      string
	DeletedAt      string
}{
	ID:             "id",
	ClassCode:      "class_code",
	ClassName:      "class_name",
	Description:    "description",
	LoreText:       "lore_text",
	Tier:           "tier",
	PromotionCount: "promotion_count",
	Icon:           "icon",
	Color:          "color",
	IsActive:       "is_active",
	IsVisible:      "is_visible",
	DisplayOrder:   "display_order",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	DeletedAt:      "deleted_at",
}

var ClassTableColumns = struct {
	ID             string
	ClassCode      string
	ClassName      string
	Description    string
	LoreText       string
	Tier           string
	PromotionCount string
	Icon           string
	Color          string
	IsActive       string
	IsVisible      string
	DisplayOrder   string
	CreatedAt      string
	UpdatedAt      string
	DeletedAt      string
}{
	ID:             "classes.id",
	ClassCode:      "classes.class_code",
	ClassName:      "classes.class_name",
	Description:    "classes.description",
	LoreText:       "classes.lore_text",
	Tier:           "classes.tier",
	PromotionCount: "classes.promotion_count",
	Icon:           "classes.icon",
	Color:          "classes.color",
	IsActive:       "classes.is_active",
	IsVisible:      "classes.is_visible",
	DisplayOrder:   "classes.display_order",
	CreatedAt:      "classes.created_at",
	UpdatedAt:      "classes.updated_at",
	DeletedAt:      "classes.deleted_at",
}

// Generated where

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ClassWhere = struct {
	ID             whereHelperstring
	ClassCode      whereHelperstring
	ClassName      whereHelperstring
	Description    whereHelpernull_String
	LoreText       whereHelpernull_String
	Tier           whereHelperstring
	PromotionCount whereHelpernull_Int16
	Icon           whereHelpernull_String
	Color          whereHelpernull_String
	IsActive       whereHelpernull_Bool
	IsVisible      whereHelpernull_Bool
	DisplayOrder   whereHelpernull_Int16
	CreatedAt      whereHelpernull_Time
	UpdatedAt      whereHelpernull_Time
	DeletedAt      whereHelpernull_Time
}{
	ID:             whereHelperstring{field: "\"classes\".\"id\""},
	ClassCode:      whereHelperstring{field: "\"classes\".\"class_code\""},
	ClassName:      whereHelperstring{field: "\"classes\".\"class_name\""},
	Description:    whereHelpernull_String{field: "\"classes\".\"description\""},
	LoreText:       whereHelpernull_String{field: "\"classes\".\"lore_text\""},
	Tier:           whereHelperstring{field: "\"classes\".\"tier\""},
	PromotionCount: whereHelpernull_Int16{field: "\"classes\".\"promotion_count\""},
	Icon:           whereHelpernull_String{field: "\"classes\".\"icon\""},
	Color:          whereHelpernull_String{field: "\"classes\".\"color\""},
	IsActive:       whereHelpernull_Bool{field: "\"classes\".\"is_active\""},
	IsVisible:      whereHelpernull_Bool{field: "\"classes\".\"is_visible\""},
	DisplayOrder:   whereHelpernull_Int16{field: "\"classes\".\"display_order\""},
	CreatedAt:      whereHelpernull_Time{field: "\"classes\".\"created_at\""},
	UpdatedAt:      whereHelpernull_Time{field: "\"classes\".\"updated_at\""},
	DeletedAt:      whereHelpernull_Time{field: "\"classes\".\"deleted_at\""},
}

// ClassRels is where relationship names are stored.
var ClassRels = struct {
	FromClassClassAdvancedRequirements string
	ToClassClassAdvancedRequirements   string
	ClassAttributeBonuses              string
	ClassTagRelations                  string
}{
	FromClassClassAdvancedRequirements: "FromClassClassAdvancedRequirements",
	ToClassClassAdvancedRequirements:   "ToClassClassAdvancedRequirements",
	ClassAttributeBonuses:              "ClassAttributeBonuses",
	ClassTagRelations:                  "ClassTagRelations",
}

// classR is where relationships are stored.
type classR struct {
	FromClassClassAdvancedRequirements ClassAdvancedRequirementSlice `boil:"FromClassClassAdvancedRequirements" json:"FromClassClassAdvancedRequirements" toml:"FromClassClassAdvancedRequirements" yaml:"FromClassClassAdvancedRequirements"`
	ToClassClassAdvancedRequirements   ClassAdvancedRequirementSlice `boil:"ToClassClassAdvancedRequirements" json:"ToClassClassAdvancedRequirements" toml:"ToClassClassAdvancedRequirements" yaml:"ToClassClassAdvancedRequirements"`
	ClassAttributeBonuses              ClassAttributeBonuseSlice     `boil:"ClassAttributeBonuses" json:"ClassAttributeBonuses" toml:"ClassAttributeBonuses" yaml:"ClassAttributeBonuses"`
	ClassTagRelations                  ClassTagRelationSlice         `boil:"ClassTagRelations" json:"ClassTagRelations" toml:"ClassTagRelations" yaml:"ClassTagRelations"`
}

// NewStruct creates a new relationship struct
func (*classR) NewStruct() *classR {
	return &classR{}
}

func (o *Class) GetFromClassClassAdvancedRequirements() ClassAdvancedRequirementSlice {
	if o == nil {
		return nil
	}

	return o.R.GetFromClassClassAdvancedRequirements()
}

func (r *classR) GetFromClassClassAdvancedRequirements() ClassAdvancedRequirementSlice {
	if r == nil {
		return nil
	}

	return r.FromClassClassAdvancedRequirements
}

func (o *Class) GetToClassClassAdvancedRequirements() ClassAdvancedRequirementSlice {
	if o == nil {
		return nil
	}

	return o.R.GetToClassClassAdvancedRequirements()
}

func (r *classR) GetToClassClassAdvancedRequirements() ClassAdvancedRequirementSlice {
	if r == nil {
		return nil
	}

	return r.ToClassClassAdvancedRequirements
}

func (o *Class) GetClassAttributeBonuses() ClassAttributeBonuseSlice {
	if o == nil {
		return nil
	}

	return o.R.GetClassAttributeBonuses()
}

func (r *classR) GetClassAttributeBonuses() ClassAttributeBonuseSlice {
	if r == nil {
		return nil
	}

	return r.ClassAttributeBonuses
}

func (o *Class) GetClassTagRelations() ClassTagRelationSlice {
	if o == nil {
		return nil
	}

	return o.R.GetClassTagRelations()
}

func (r *classR) GetClassTagRelations() ClassTagRelationSlice {
	if r == nil {
		return nil
	}

	return r.ClassTagRelations
}

// classL is where Load methods for each relationship are stored.
type classL struct{}

var (
	classAllColumns            = []string{"id", "class_code", "class_name", "description", "lore_text", "tier", "promotion_count", "icon", "color", "is_active", "is_visible", "display_order", "created_at", "updated_at", "deleted_at"}
	classColumnsWithoutDefault = []string{"class_code", "class_name", "tier"}
	classColumnsWithDefault    = []string{"id", "description", "lore_text", "promotion_count", "icon", "color", "is_active", "is_visible", "display_order", "created_at", "updated_at", "deleted_at"}
	classPrimaryKeyColumns     = []string{"id"}
	classGeneratedColumns      = []string{}
)

type (
	// ClassSlice is an alias for a slice of pointers to Class.
	// This should almost always be used instead of []Class.
	ClassSlice []*Class
	// ClassHook is the signature for custom Class hook methods
	ClassHook func(context.Context, boil.ContextExecutor, *Class) error

	classQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	classType                 = reflect.TypeOf(&Class{})
	classMapping              = queries.MakeStructMapping(classType)
	classPrimaryKeyMapping, _ = queries.BindMapping(classType, classMapping, classPrimaryKeyColumns)
	classInsertCacheMut       sync.RWMutex
	classInsertCache          = make(map[string]insertCache)
	classUpdateCacheMut       sync.RWMutex
	classUpdateCache          = make(map[string]updateCache)
	classUpsertCacheMut       sync.RWMutex
	classUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var classAfterSelectMu sync.Mutex
var classAfterSelectHooks []ClassHook

var classBeforeInsertMu sync.Mutex
var classBeforeInsertHooks []ClassHook
var classAfterInsertMu sync.Mutex
var classAfterInsertHooks []ClassHook

var classBeforeUpdateMu sync.Mutex
var classBeforeUpdateHooks []ClassHook
var classAfterUpdateMu sync.Mutex
var classAfterUpdateHooks []ClassHook

var classBeforeDeleteMu sync.Mutex
var classBeforeDeleteHooks []ClassHook
var classAfterDeleteMu sync.Mutex
var classAfterDeleteHooks []ClassHook

var classBeforeUpsertMu sync.Mutex
var classBeforeUpsertHooks []ClassHook
var classAfterUpsertMu sync.Mutex
var classAfterUpsertHooks []ClassHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Class) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Class) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Class) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Class) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Class) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Class) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Class) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Class) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Class) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range classAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddClassHook registers your hook function for all future operations.
func AddClassHook(hookPoint boil.HookPoint, classHook ClassHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		classAfterSelectMu.Lock()
		classAfterSelectHooks = append(classAfterSelectHooks, classHook)
		classAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		classBeforeInsertMu.Lock()
		classBeforeInsertHooks = append(classBeforeInsertHooks, classHook)
		classBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		classAfterInsertMu.Lock()
		classAfterInsertHooks = append(classAfterInsertHooks, classHook)
		classAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		classBeforeUpdateMu.Lock()
		classBeforeUpdateHooks = append(classBeforeUpdateHooks, classHook)
		classBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		classAfterUpdateMu.Lock()
		classAfterUpdateHooks = append(classAfterUpdateHooks, classHook)
		classAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		classBeforeDeleteMu.Lock()
		classBeforeDeleteHooks = append(classBeforeDeleteHooks, classHook)
		classBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		classAfterDeleteMu.Lock()
		classAfterDeleteHooks = append(classAfterDeleteHooks, classHook)
		classAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		classBeforeUpsertMu.Lock()
		classBeforeUpsertHooks = append(classBeforeUpsertHooks, classHook)
		classBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		classAfterUpsertMu.Lock()
		classAfterUpsertHooks = append(classAfterUpsertHooks, classHook)
		classAfterUpsertMu.Unlock()
	}
}

// One returns a single class record from the query.
func (q classQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Class, error) {
	o := &Class{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for classes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Class records from the query.
func (q classQuery) All(ctx context.Context, exec boil.ContextExecutor) (ClassSlice, error) {
	var o []*Class

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to Class slice")
	}

	if len(classAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Class records in the query.
func (q classQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count classes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q classQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if classes exists")
	}

	return count > 0, nil
}

// FromClassClassAdvancedRequirements retrieves all the class_advanced_requirement's ClassAdvancedRequirements with an executor via from_class_id column.
func (o *Class) FromClassClassAdvancedRequirements(mods ...qm.QueryMod) classAdvancedRequirementQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"class_advanced_requirements\".\"from_class_id\"=?", o.ID),
	)

	return ClassAdvancedRequirements(queryMods...)
}

// ToClassClassAdvancedRequirements retrieves all the class_advanced_requirement's ClassAdvancedRequirements with an executor via to_class_id column.
func (o *Class) ToClassClassAdvancedRequirements(mods ...qm.QueryMod) classAdvancedRequirementQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"class_advanced_requirements\".\"to_class_id\"=?", o.ID),
	)

	return ClassAdvancedRequirements(queryMods...)
}

// ClassAttributeBonuses retrieves all the class_attribute_bonuse's ClassAttributeBonuses with an executor.
func (o *Class) ClassAttributeBonuses(mods ...qm.QueryMod) classAttributeBonuseQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"class_attribute_bonuses\".\"class_id\"=?", o.ID),
	)

	return ClassAttributeBonuses(queryMods...)
}

// ClassTagRelations retrieves all the class_tag_relation's ClassTagRelations with an executor.
func (o *Class) ClassTagRelations(mods ...qm.QueryMod) classTagRelationQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"class_tag_relations\".\"class_id\"=?", o.ID),
	)

	return ClassTagRelations(queryMods...)
}

// LoadFromClassClassAdvancedRequirements allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (classL) LoadFromClassClassAdvancedRequirements(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClass interface{}, mods queries.Applicator) error {
	var slice []*Class
	var object *Class

	if singular {
		var ok bool
		object, ok = maybeClass.(*Class)
		if !ok {
			object = new(Class)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClass))
			}
		}
	} else {
		s, ok := maybeClass.(*[]*Class)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClass))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &classR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`class_advanced_requirements`),
		qm.WhereIn(`class_advanced_requirements.from_class_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load class_advanced_requirements")
	}

	var resultSlice []*ClassAdvancedRequirement
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice class_advanced_requirements")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on class_advanced_requirements")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for class_advanced_requirements")
	}

	if len(classAdvancedRequirementAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FromClassClassAdvancedRequirements = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &classAdvancedRequirementR{}
			}
			foreign.R.FromClass = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FromClassID {
				local.R.FromClassClassAdvancedRequirements = append(local.R.FromClassClassAdvancedRequirements, foreign)
				if foreign.R == nil {
					foreign.R = &classAdvancedRequirementR{}
				}
				foreign.R.FromClass = local
				break
			}
		}
	}

	return nil
}

// LoadToClassClassAdvancedRequirements allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (classL) LoadToClassClassAdvancedRequirements(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClass interface{}, mods queries.Applicator) error {
	var slice []*Class
	var object *Class

	if singular {
		var ok bool
		object, ok = maybeClass.(*Class)
		if !ok {
			object = new(Class)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClass))
			}
		}
	} else {
		s, ok := maybeClass.(*[]*Class)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClass))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &classR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`class_advanced_requirements`),
		qm.WhereIn(`class_advanced_requirements.to_class_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load class_advanced_requirements")
	}

	var resultSlice []*ClassAdvancedRequirement
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice class_advanced_requirements")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on class_advanced_requirements")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for class_advanced_requirements")
	}

	if len(classAdvancedRequirementAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ToClassClassAdvancedRequirements = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &classAdvancedRequirementR{}
			}
			foreign.R.ToClass = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ToClassID {
				local.R.ToClassClassAdvancedRequirements = append(local.R.ToClassClassAdvancedRequirements, foreign)
				if foreign.R == nil {
					foreign.R = &classAdvancedRequirementR{}
				}
				foreign.R.ToClass = local
				break
			}
		}
	}

	return nil
}

// LoadClassAttributeBonuses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (classL) LoadClassAttributeBonuses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClass interface{}, mods queries.Applicator) error {
	var slice []*Class
	var object *Class

	if singular {
		var ok bool
		object, ok = maybeClass.(*Class)
		if !ok {
			object = new(Class)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClass))
			}
		}
	} else {
		s, ok := maybeClass.(*[]*Class)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClass))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &classR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`class_attribute_bonuses`),
		qm.WhereIn(`class_attribute_bonuses.class_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load class_attribute_bonuses")
	}

	var resultSlice []*ClassAttributeBonuse
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice class_attribute_bonuses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on class_attribute_bonuses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for class_attribute_bonuses")
	}

	if len(classAttributeBonuseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ClassAttributeBonuses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &classAttributeBonuseR{}
			}
			foreign.R.Class = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ClassID {
				local.R.ClassAttributeBonuses = append(local.R.ClassAttributeBonuses, foreign)
				if foreign.R == nil {
					foreign.R = &classAttributeBonuseR{}
				}
				foreign.R.Class = local
				break
			}
		}
	}

	return nil
}

// LoadClassTagRelations allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (classL) LoadClassTagRelations(ctx context.Context, e boil.ContextExecutor, singular bool, maybeClass interface{}, mods queries.Applicator) error {
	var slice []*Class
	var object *Class

	if singular {
		var ok bool
		object, ok = maybeClass.(*Class)
		if !ok {
			object = new(Class)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClass))
			}
		}
	} else {
		s, ok := maybeClass.(*[]*Class)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClass))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &classR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`class_tag_relations`),
		qm.WhereIn(`class_tag_relations.class_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load class_tag_relations")
	}

	var resultSlice []*ClassTagRelation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice class_tag_relations")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on class_tag_relations")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for class_tag_relations")
	}

	if len(classTagRelationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ClassTagRelations = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &classTagRelationR{}
			}
			foreign.R.Class = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ClassID {
				local.R.ClassTagRelations = append(local.R.ClassTagRelations, foreign)
				if foreign.R == nil {
					foreign.R = &classTagRelationR{}
				}
				foreign.R.Class = local
				break
			}
		}
	}

	return nil
}

// AddFromClassClassAdvancedRequirements adds the given related objects to the existing relationships
// of the class, optionally inserting them as new records.
// Appends related to o.R.FromClassClassAdvancedRequirements.
// Sets related.R.FromClass appropriately.
func (o *Class) AddFromClassClassAdvancedRequirements(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ClassAdvancedRequirement) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FromClassID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"class_advanced_requirements\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"from_class_id"}),
				strmangle.WhereClause("\"", "\"", 2, classAdvancedRequirementPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FromClassID = o.ID
		}
	}

	if o.R == nil {
		o.R = &classR{
			FromClassClassAdvancedRequirements: related,
		}
	} else {
		o.R.FromClassClassAdvancedRequirements = append(o.R.FromClassClassAdvancedRequirements, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &classAdvancedRequirementR{
				FromClass: o,
			}
		} else {
			rel.R.FromClass = o
		}
	}
	return nil
}

// AddToClassClassAdvancedRequirements adds the given related objects to the existing relationships
// of the class, optionally inserting them as new records.
// Appends related to o.R.ToClassClassAdvancedRequirements.
// Sets related.R.ToClass appropriately.
func (o *Class) AddToClassClassAdvancedRequirements(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ClassAdvancedRequirement) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ToClassID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"class_advanced_requirements\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"to_class_id"}),
				strmangle.WhereClause("\"", "\"", 2, classAdvancedRequirementPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ToClassID = o.ID
		}
	}

	if o.R == nil {
		o.R = &classR{
			ToClassClassAdvancedRequirements: related,
		}
	} else {
		o.R.ToClassClassAdvancedRequirements = append(o.R.ToClassClassAdvancedRequirements, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &classAdvancedRequirementR{
				ToClass: o,
			}
		} else {
			rel.R.ToClass = o
		}
	}
	return nil
}

// AddClassAttributeBonuses adds the given related objects to the existing relationships
// of the class, optionally inserting them as new records.
// Appends related to o.R.ClassAttributeBonuses.
// Sets related.R.Class appropriately.
func (o *Class) AddClassAttributeBonuses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ClassAttributeBonuse) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ClassID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"class_attribute_bonuses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"class_id"}),
				strmangle.WhereClause("\"", "\"", 2, classAttributeBonusePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ClassID = o.ID
		}
	}

	if o.R == nil {
		o.R = &classR{
			ClassAttributeBonuses: related,
		}
	} else {
		o.R.ClassAttributeBonuses = append(o.R.ClassAttributeBonuses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &classAttributeBonuseR{
				Class: o,
			}
		} else {
			rel.R.Class = o
		}
	}
	return nil
}

// AddClassTagRelations adds the given related objects to the existing relationships
// of the class, optionally inserting them as new records.
// Appends related to o.R.ClassTagRelations.
// Sets related.R.Class appropriately.
func (o *Class) AddClassTagRelations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ClassTagRelation) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ClassID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"class_tag_relations\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"class_id"}),
				strmangle.WhereClause("\"", "\"", 2, classTagRelationPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ClassID = o.ID
		}
	}

	if o.R == nil {
		o.R = &classR{
			ClassTagRelations: related,
		}
	} else {
		o.R.ClassTagRelations = append(o.R.ClassTagRelations, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &classTagRelationR{
				Class: o,
			}
		} else {
			rel.R.Class = o
		}
	}
	return nil
}

// Classes retrieves all the records using an executor.
func Classes(mods ...qm.QueryMod) classQuery {
	mods = append(mods, qm.From("\"classes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"classes\".*"})
	}

	return classQuery{q}
}

// FindClass retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindClass(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Class, error) {
	classObj := &Class{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"classes\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, classObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from classes")
	}

	if err = classObj.doAfterSelectHooks(ctx, exec); err != nil {
		return classObj, err
	}

	return classObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Class) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no classes provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(classColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	classInsertCacheMut.RLock()
	cache, cached := classInsertCache[key]
	classInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			classAllColumns,
			classColumnsWithDefault,
			classColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(classType, classMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(classType, classMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"classes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"classes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into classes")
	}

	if !cached {
		classInsertCacheMut.Lock()
		classInsertCache[key] = cache
		classInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Class.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Class) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	classUpdateCacheMut.RLock()
	cache, cached := classUpdateCache[key]
	classUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			classAllColumns,
			classPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update classes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"classes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, classPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(classType, classMapping, append(wl, classPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update classes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for classes")
	}

	if !cached {
		classUpdateCacheMut.Lock()
		classUpdateCache[key] = cache
		classUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q classQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for classes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for classes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ClassSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"classes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, classPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in class slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all class")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Class) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no classes provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(classColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	classUpsertCacheMut.RLock()
	cache, cached := classUpsertCache[key]
	classUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			classAllColumns,
			classColumnsWithDefault,
			classColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			classAllColumns,
			classPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert classes, could not build update column list")
		}

		ret := strmangle.SetComplement(classAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(classPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert classes, could not build conflict column list")
			}

			conflict = make([]string, len(classPrimaryKeyColumns))
			copy(conflict, classPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"classes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(classType, classMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(classType, classMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert classes")
	}

	if !cached {
		classUpsertCacheMut.Lock()
		classUpsertCache[key] = cache
		classUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Class record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Class) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no Class provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), classPrimaryKeyMapping)
	sql := "DELETE FROM \"classes\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from classes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for classes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q classQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no classQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from classes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for classes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ClassSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(classBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"classes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, classPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from class slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for classes")
	}

	if len(classAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Class) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindClass(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ClassSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ClassSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"classes\".* FROM \"classes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, classPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in ClassSlice")
	}

	*o = slice

	return nil
}

// ClassExists checks if the Class row exists.
func ClassExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"classes\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if classes exists")
	}

	return exists, nil
}

// Exists checks if the Class row exists.
func (o *Class) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ClassExists(ctx, exec, o.ID)
}
