// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserLoginHistory is an object representing the database table.
type UserLoginHistory struct {
	ID              int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID          string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	LoginTime       time.Time   `boil:"login_time" json:"login_time" toml:"login_time" yaml:"login_time"`
	LogoutTime      null.Time   `boil:"logout_time" json:"logout_time,omitempty" toml:"logout_time" yaml:"logout_time,omitempty"`
	SessionDuration null.Int    `boil:"session_duration" json:"session_duration,omitempty" toml:"session_duration" yaml:"session_duration,omitempty"`
	IPAddress       string      `boil:"ip_address" json:"ip_address" toml:"ip_address" yaml:"ip_address"`
	UserAgent       null.String `boil:"user_agent" json:"user_agent,omitempty" toml:"user_agent" yaml:"user_agent,omitempty"`
	DeviceType      null.String `boil:"device_type" json:"device_type,omitempty" toml:"device_type" yaml:"device_type,omitempty"`
	BrowserName     null.String `boil:"browser_name" json:"browser_name,omitempty" toml:"browser_name" yaml:"browser_name,omitempty"`
	BrowserVersion  null.String `boil:"browser_version" json:"browser_version,omitempty" toml:"browser_version" yaml:"browser_version,omitempty"`
	OsName          null.String `boil:"os_name" json:"os_name,omitempty" toml:"os_name" yaml:"os_name,omitempty"`
	OsVersion       null.String `boil:"os_version" json:"os_version,omitempty" toml:"os_version" yaml:"os_version,omitempty"`
	Country         null.String `boil:"country" json:"country,omitempty" toml:"country" yaml:"country,omitempty"`
	Region          null.String `boil:"region" json:"region,omitempty" toml:"region" yaml:"region,omitempty"`
	City            null.String `boil:"city" json:"city,omitempty" toml:"city" yaml:"city,omitempty"`
	LoginMethod     string      `boil:"login_method" json:"login_method" toml:"login_method" yaml:"login_method"`
	OauthProvider   null.String `boil:"oauth_provider" json:"oauth_provider,omitempty" toml:"oauth_provider" yaml:"oauth_provider,omitempty"`
	IsSuspicious    bool        `boil:"is_suspicious" json:"is_suspicious" toml:"is_suspicious" yaml:"is_suspicious"`
	RiskScore       null.Int    `boil:"risk_score" json:"risk_score,omitempty" toml:"risk_score" yaml:"risk_score,omitempty"`
	Status          string      `boil:"status" json:"status" toml:"status" yaml:"status"`

	R *userLoginHistoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userLoginHistoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserLoginHistoryColumns = struct {
	ID              string
	UserID          string
	LoginTime       string
	LogoutTime      string
	SessionDuration string
	IPAddress       string
	UserAgent       string
	DeviceType      string
	BrowserName     string
	BrowserVersion  string
	OsName          string
	OsVersion       string
	Country         string
	Region          string
	City            string
	LoginMethod     string
	OauthProvider   string
	IsSuspicious    string
	RiskScore       string
	Status          string
}{
	ID:              "id",
	UserID:          "user_id",
	LoginTime:       "login_time",
	LogoutTime:      "logout_time",
	SessionDuration: "session_duration",
	IPAddress:       "ip_address",
	UserAgent:       "user_agent",
	DeviceType:      "device_type",
	BrowserName:     "browser_name",
	BrowserVersion:  "browser_version",
	OsName:          "os_name",
	OsVersion:       "os_version",
	Country:         "country",
	Region:          "region",
	City:            "city",
	LoginMethod:     "login_method",
	OauthProvider:   "oauth_provider",
	IsSuspicious:    "is_suspicious",
	RiskScore:       "risk_score",
	Status:          "status",
}

var UserLoginHistoryTableColumns = struct {
	ID              string
	UserID          string
	LoginTime       string
	LogoutTime      string
	SessionDuration string
	IPAddress       string
	UserAgent       string
	DeviceType      string
	BrowserName     string
	BrowserVersion  string
	OsName          string
	OsVersion       string
	Country         string
	Region          string
	City            string
	LoginMethod     string
	OauthProvider   string
	IsSuspicious    string
	RiskScore       string
	Status          string
}{
	ID:              "user_login_history.id",
	UserID:          "user_login_history.user_id",
	LoginTime:       "user_login_history.login_time",
	LogoutTime:      "user_login_history.logout_time",
	SessionDuration: "user_login_history.session_duration",
	IPAddress:       "user_login_history.ip_address",
	UserAgent:       "user_login_history.user_agent",
	DeviceType:      "user_login_history.device_type",
	BrowserName:     "user_login_history.browser_name",
	BrowserVersion:  "user_login_history.browser_version",
	OsName:          "user_login_history.os_name",
	OsVersion:       "user_login_history.os_version",
	Country:         "user_login_history.country",
	Region:          "user_login_history.region",
	City:            "user_login_history.city",
	LoginMethod:     "user_login_history.login_method",
	OauthProvider:   "user_login_history.oauth_provider",
	IsSuspicious:    "user_login_history.is_suspicious",
	RiskScore:       "user_login_history.risk_score",
	Status:          "user_login_history.status",
}

// Generated where

var UserLoginHistoryWhere = struct {
	ID              whereHelperint64
	UserID          whereHelperstring
	LoginTime       whereHelpertime_Time
	LogoutTime      whereHelpernull_Time
	SessionDuration whereHelpernull_Int
	IPAddress       whereHelperstring
	UserAgent       whereHelpernull_String
	DeviceType      whereHelpernull_String
	BrowserName     whereHelpernull_String
	BrowserVersion  whereHelpernull_String
	OsName          whereHelpernull_String
	OsVersion       whereHelpernull_String
	Country         whereHelpernull_String
	Region          whereHelpernull_String
	City            whereHelpernull_String
	LoginMethod     whereHelperstring
	OauthProvider   whereHelpernull_String
	IsSuspicious    whereHelperbool
	RiskScore       whereHelpernull_Int
	Status          whereHelperstring
}{
	ID:              whereHelperint64{field: "\"user_login_history\".\"id\""},
	UserID:          whereHelperstring{field: "\"user_login_history\".\"user_id\""},
	LoginTime:       whereHelpertime_Time{field: "\"user_login_history\".\"login_time\""},
	LogoutTime:      whereHelpernull_Time{field: "\"user_login_history\".\"logout_time\""},
	SessionDuration: whereHelpernull_Int{field: "\"user_login_history\".\"session_duration\""},
	IPAddress:       whereHelperstring{field: "\"user_login_history\".\"ip_address\""},
	UserAgent:       whereHelpernull_String{field: "\"user_login_history\".\"user_agent\""},
	DeviceType:      whereHelpernull_String{field: "\"user_login_history\".\"device_type\""},
	BrowserName:     whereHelpernull_String{field: "\"user_login_history\".\"browser_name\""},
	BrowserVersion:  whereHelpernull_String{field: "\"user_login_history\".\"browser_version\""},
	OsName:          whereHelpernull_String{field: "\"user_login_history\".\"os_name\""},
	OsVersion:       whereHelpernull_String{field: "\"user_login_history\".\"os_version\""},
	Country:         whereHelpernull_String{field: "\"user_login_history\".\"country\""},
	Region:          whereHelpernull_String{field: "\"user_login_history\".\"region\""},
	City:            whereHelpernull_String{field: "\"user_login_history\".\"city\""},
	LoginMethod:     whereHelperstring{field: "\"user_login_history\".\"login_method\""},
	OauthProvider:   whereHelpernull_String{field: "\"user_login_history\".\"oauth_provider\""},
	IsSuspicious:    whereHelperbool{field: "\"user_login_history\".\"is_suspicious\""},
	RiskScore:       whereHelpernull_Int{field: "\"user_login_history\".\"risk_score\""},
	Status:          whereHelperstring{field: "\"user_login_history\".\"status\""},
}

// UserLoginHistoryRels is where relationship names are stored.
var UserLoginHistoryRels = struct {
	User string
}{
	User: "User",
}

// userLoginHistoryR is where relationships are stored.
type userLoginHistoryR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userLoginHistoryR) NewStruct() *userLoginHistoryR {
	return &userLoginHistoryR{}
}

func (o *UserLoginHistory) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *userLoginHistoryR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// userLoginHistoryL is where Load methods for each relationship are stored.
type userLoginHistoryL struct{}

var (
	userLoginHistoryAllColumns            = []string{"id", "user_id", "login_time", "logout_time", "session_duration", "ip_address", "user_agent", "device_type", "browser_name", "browser_version", "os_name", "os_version", "country", "region", "city", "login_method", "oauth_provider", "is_suspicious", "risk_score", "status"}
	userLoginHistoryColumnsWithoutDefault = []string{"user_id", "ip_address"}
	userLoginHistoryColumnsWithDefault    = []string{"id", "login_time", "logout_time", "session_duration", "user_agent", "device_type", "browser_name", "browser_version", "os_name", "os_version", "country", "region", "city", "login_method", "oauth_provider", "is_suspicious", "risk_score", "status"}
	userLoginHistoryPrimaryKeyColumns     = []string{"id"}
	userLoginHistoryGeneratedColumns      = []string{}
)

type (
	// UserLoginHistorySlice is an alias for a slice of pointers to UserLoginHistory.
	// This should almost always be used instead of []UserLoginHistory.
	UserLoginHistorySlice []*UserLoginHistory
	// UserLoginHistoryHook is the signature for custom UserLoginHistory hook methods
	UserLoginHistoryHook func(context.Context, boil.ContextExecutor, *UserLoginHistory) error

	userLoginHistoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userLoginHistoryType                 = reflect.TypeOf(&UserLoginHistory{})
	userLoginHistoryMapping              = queries.MakeStructMapping(userLoginHistoryType)
	userLoginHistoryPrimaryKeyMapping, _ = queries.BindMapping(userLoginHistoryType, userLoginHistoryMapping, userLoginHistoryPrimaryKeyColumns)
	userLoginHistoryInsertCacheMut       sync.RWMutex
	userLoginHistoryInsertCache          = make(map[string]insertCache)
	userLoginHistoryUpdateCacheMut       sync.RWMutex
	userLoginHistoryUpdateCache          = make(map[string]updateCache)
	userLoginHistoryUpsertCacheMut       sync.RWMutex
	userLoginHistoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userLoginHistoryAfterSelectMu sync.Mutex
var userLoginHistoryAfterSelectHooks []UserLoginHistoryHook

var userLoginHistoryBeforeInsertMu sync.Mutex
var userLoginHistoryBeforeInsertHooks []UserLoginHistoryHook
var userLoginHistoryAfterInsertMu sync.Mutex
var userLoginHistoryAfterInsertHooks []UserLoginHistoryHook

var userLoginHistoryBeforeUpdateMu sync.Mutex
var userLoginHistoryBeforeUpdateHooks []UserLoginHistoryHook
var userLoginHistoryAfterUpdateMu sync.Mutex
var userLoginHistoryAfterUpdateHooks []UserLoginHistoryHook

var userLoginHistoryBeforeDeleteMu sync.Mutex
var userLoginHistoryBeforeDeleteHooks []UserLoginHistoryHook
var userLoginHistoryAfterDeleteMu sync.Mutex
var userLoginHistoryAfterDeleteHooks []UserLoginHistoryHook

var userLoginHistoryBeforeUpsertMu sync.Mutex
var userLoginHistoryBeforeUpsertHooks []UserLoginHistoryHook
var userLoginHistoryAfterUpsertMu sync.Mutex
var userLoginHistoryAfterUpsertHooks []UserLoginHistoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserLoginHistory) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserLoginHistory) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserLoginHistory) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserLoginHistory) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserLoginHistory) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserLoginHistory) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserLoginHistory) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserLoginHistory) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserLoginHistory) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userLoginHistoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserLoginHistoryHook registers your hook function for all future operations.
func AddUserLoginHistoryHook(hookPoint boil.HookPoint, userLoginHistoryHook UserLoginHistoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userLoginHistoryAfterSelectMu.Lock()
		userLoginHistoryAfterSelectHooks = append(userLoginHistoryAfterSelectHooks, userLoginHistoryHook)
		userLoginHistoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userLoginHistoryBeforeInsertMu.Lock()
		userLoginHistoryBeforeInsertHooks = append(userLoginHistoryBeforeInsertHooks, userLoginHistoryHook)
		userLoginHistoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userLoginHistoryAfterInsertMu.Lock()
		userLoginHistoryAfterInsertHooks = append(userLoginHistoryAfterInsertHooks, userLoginHistoryHook)
		userLoginHistoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userLoginHistoryBeforeUpdateMu.Lock()
		userLoginHistoryBeforeUpdateHooks = append(userLoginHistoryBeforeUpdateHooks, userLoginHistoryHook)
		userLoginHistoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userLoginHistoryAfterUpdateMu.Lock()
		userLoginHistoryAfterUpdateHooks = append(userLoginHistoryAfterUpdateHooks, userLoginHistoryHook)
		userLoginHistoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userLoginHistoryBeforeDeleteMu.Lock()
		userLoginHistoryBeforeDeleteHooks = append(userLoginHistoryBeforeDeleteHooks, userLoginHistoryHook)
		userLoginHistoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userLoginHistoryAfterDeleteMu.Lock()
		userLoginHistoryAfterDeleteHooks = append(userLoginHistoryAfterDeleteHooks, userLoginHistoryHook)
		userLoginHistoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userLoginHistoryBeforeUpsertMu.Lock()
		userLoginHistoryBeforeUpsertHooks = append(userLoginHistoryBeforeUpsertHooks, userLoginHistoryHook)
		userLoginHistoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userLoginHistoryAfterUpsertMu.Lock()
		userLoginHistoryAfterUpsertHooks = append(userLoginHistoryAfterUpsertHooks, userLoginHistoryHook)
		userLoginHistoryAfterUpsertMu.Unlock()
	}
}

// OneG returns a single userLoginHistory record from the query using the global executor.
func (q userLoginHistoryQuery) OneG(ctx context.Context) (*UserLoginHistory, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single userLoginHistory record from the query using the global executor, and panics on error.
func (q userLoginHistoryQuery) OneGP(ctx context.Context) *UserLoginHistory {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single userLoginHistory record from the query, and panics on error.
func (q userLoginHistoryQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *UserLoginHistory {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single userLoginHistory record from the query.
func (q userLoginHistoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserLoginHistory, error) {
	o := &UserLoginHistory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for user_login_history")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all UserLoginHistory records from the query using the global executor.
func (q userLoginHistoryQuery) AllG(ctx context.Context) (UserLoginHistorySlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all UserLoginHistory records from the query using the global executor, and panics on error.
func (q userLoginHistoryQuery) AllGP(ctx context.Context) UserLoginHistorySlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all UserLoginHistory records from the query, and panics on error.
func (q userLoginHistoryQuery) AllP(ctx context.Context, exec boil.ContextExecutor) UserLoginHistorySlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all UserLoginHistory records from the query.
func (q userLoginHistoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserLoginHistorySlice, error) {
	var o []*UserLoginHistory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to UserLoginHistory slice")
	}

	if len(userLoginHistoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all UserLoginHistory records in the query using the global executor
func (q userLoginHistoryQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all UserLoginHistory records in the query using the global executor, and panics on error.
func (q userLoginHistoryQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all UserLoginHistory records in the query, and panics on error.
func (q userLoginHistoryQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all UserLoginHistory records in the query.
func (q userLoginHistoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count user_login_history rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q userLoginHistoryQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q userLoginHistoryQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q userLoginHistoryQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q userLoginHistoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if user_login_history exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserLoginHistory) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userLoginHistoryL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserLoginHistory interface{}, mods queries.Applicator) error {
	var slice []*UserLoginHistory
	var object *UserLoginHistory

	if singular {
		var ok bool
		object, ok = maybeUserLoginHistory.(*UserLoginHistory)
		if !ok {
			object = new(UserLoginHistory)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserLoginHistory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserLoginHistory))
			}
		}
	} else {
		s, ok := maybeUserLoginHistory.(*[]*UserLoginHistory)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserLoginHistory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserLoginHistory))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userLoginHistoryR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userLoginHistoryR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`users.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserLoginHistories = append(foreign.R.UserLoginHistories, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserLoginHistories = append(foreign.R.UserLoginHistories, local)
				break
			}
		}
	}

	return nil
}

// SetUserG of the userLoginHistory to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserLoginHistories.
// Uses the global database handle.
func (o *UserLoginHistory) SetUserG(ctx context.Context, insert bool, related *User) error {
	return o.SetUser(ctx, boil.GetContextDB(), insert, related)
}

// SetUserP of the userLoginHistory to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserLoginHistories.
// Panics on error.
func (o *UserLoginHistory) SetUserP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) {
	if err := o.SetUser(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUserGP of the userLoginHistory to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserLoginHistories.
// Uses the global database handle and panics on error.
func (o *UserLoginHistory) SetUserGP(ctx context.Context, insert bool, related *User) {
	if err := o.SetUser(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUser of the userLoginHistory to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserLoginHistories.
func (o *UserLoginHistory) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_login_history\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userLoginHistoryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userLoginHistoryR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserLoginHistories: UserLoginHistorySlice{o},
		}
	} else {
		related.R.UserLoginHistories = append(related.R.UserLoginHistories, o)
	}

	return nil
}

// UserLoginHistories retrieves all the records using an executor.
func UserLoginHistories(mods ...qm.QueryMod) userLoginHistoryQuery {
	mods = append(mods, qm.From("\"user_login_history\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_login_history\".*"})
	}

	return userLoginHistoryQuery{q}
}

// FindUserLoginHistoryG retrieves a single record by ID.
func FindUserLoginHistoryG(ctx context.Context, iD int64, selectCols ...string) (*UserLoginHistory, error) {
	return FindUserLoginHistory(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindUserLoginHistoryP retrieves a single record by ID with an executor, and panics on error.
func FindUserLoginHistoryP(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) *UserLoginHistory {
	retobj, err := FindUserLoginHistory(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindUserLoginHistoryGP retrieves a single record by ID, and panics on error.
func FindUserLoginHistoryGP(ctx context.Context, iD int64, selectCols ...string) *UserLoginHistory {
	retobj, err := FindUserLoginHistory(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindUserLoginHistory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserLoginHistory(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*UserLoginHistory, error) {
	userLoginHistoryObj := &UserLoginHistory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_login_history\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userLoginHistoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from user_login_history")
	}

	if err = userLoginHistoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userLoginHistoryObj, err
	}

	return userLoginHistoryObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UserLoginHistory) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *UserLoginHistory) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *UserLoginHistory) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserLoginHistory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no user_login_history provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userLoginHistoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userLoginHistoryInsertCacheMut.RLock()
	cache, cached := userLoginHistoryInsertCache[key]
	userLoginHistoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userLoginHistoryAllColumns,
			userLoginHistoryColumnsWithDefault,
			userLoginHistoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userLoginHistoryType, userLoginHistoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userLoginHistoryType, userLoginHistoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_login_history\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_login_history\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into user_login_history")
	}

	if !cached {
		userLoginHistoryInsertCacheMut.Lock()
		userLoginHistoryInsertCache[key] = cache
		userLoginHistoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single UserLoginHistory record using the global executor.
// See Update for more documentation.
func (o *UserLoginHistory) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the UserLoginHistory, and panics on error.
// See Update for more documentation.
func (o *UserLoginHistory) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single UserLoginHistory record using the global executor. Panics on error.
// See Update for more documentation.
func (o *UserLoginHistory) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the UserLoginHistory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserLoginHistory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userLoginHistoryUpdateCacheMut.RLock()
	cache, cached := userLoginHistoryUpdateCache[key]
	userLoginHistoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userLoginHistoryAllColumns,
			userLoginHistoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update user_login_history, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_login_history\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userLoginHistoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userLoginHistoryType, userLoginHistoryMapping, append(wl, userLoginHistoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update user_login_history row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for user_login_history")
	}

	if !cached {
		userLoginHistoryUpdateCacheMut.Lock()
		userLoginHistoryUpdateCache[key] = cache
		userLoginHistoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q userLoginHistoryQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q userLoginHistoryQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q userLoginHistoryQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q userLoginHistoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for user_login_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for user_login_history")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UserLoginHistorySlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o UserLoginHistorySlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o UserLoginHistorySlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserLoginHistorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userLoginHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_login_history\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userLoginHistoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in userLoginHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all userLoginHistory")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UserLoginHistory) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *UserLoginHistory) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *UserLoginHistory) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserLoginHistory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no user_login_history provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userLoginHistoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userLoginHistoryUpsertCacheMut.RLock()
	cache, cached := userLoginHistoryUpsertCache[key]
	userLoginHistoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userLoginHistoryAllColumns,
			userLoginHistoryColumnsWithDefault,
			userLoginHistoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userLoginHistoryAllColumns,
			userLoginHistoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert user_login_history, could not build update column list")
		}

		ret := strmangle.SetComplement(userLoginHistoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userLoginHistoryPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert user_login_history, could not build conflict column list")
			}

			conflict = make([]string, len(userLoginHistoryPrimaryKeyColumns))
			copy(conflict, userLoginHistoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_login_history\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userLoginHistoryType, userLoginHistoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userLoginHistoryType, userLoginHistoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert user_login_history")
	}

	if !cached {
		userLoginHistoryUpsertCacheMut.Lock()
		userLoginHistoryUpsertCache[key] = cache
		userLoginHistoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single UserLoginHistory record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UserLoginHistory) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// DeleteP deletes a single UserLoginHistory record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UserLoginHistory) DeleteP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.Delete(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single UserLoginHistory record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *UserLoginHistory) DeleteGP(ctx context.Context) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single UserLoginHistory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserLoginHistory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no UserLoginHistory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userLoginHistoryPrimaryKeyMapping)
	sql := "DELETE FROM \"user_login_history\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from user_login_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for user_login_history")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q userLoginHistoryQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows, and panics on error.
func (q userLoginHistoryQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q userLoginHistoryQuery) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q userLoginHistoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no userLoginHistoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from user_login_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for user_login_history")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o UserLoginHistorySlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o UserLoginHistorySlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o UserLoginHistorySlice) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserLoginHistorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userLoginHistoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userLoginHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_login_history\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userLoginHistoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from userLoginHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for user_login_history")
	}

	if len(userLoginHistoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UserLoginHistory) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("entity: no UserLoginHistory provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *UserLoginHistory) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *UserLoginHistory) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserLoginHistory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserLoginHistory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserLoginHistorySlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("entity: empty UserLoginHistorySlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UserLoginHistorySlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *UserLoginHistorySlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserLoginHistorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserLoginHistorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userLoginHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_login_history\".* FROM \"user_login_history\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userLoginHistoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in UserLoginHistorySlice")
	}

	*o = slice

	return nil
}

// UserLoginHistoryExistsG checks if the UserLoginHistory row exists.
func UserLoginHistoryExistsG(ctx context.Context, iD int64) (bool, error) {
	return UserLoginHistoryExists(ctx, boil.GetContextDB(), iD)
}

// UserLoginHistoryExistsP checks if the UserLoginHistory row exists. Panics on error.
func UserLoginHistoryExistsP(ctx context.Context, exec boil.ContextExecutor, iD int64) bool {
	e, err := UserLoginHistoryExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// UserLoginHistoryExistsGP checks if the UserLoginHistory row exists. Panics on error.
func UserLoginHistoryExistsGP(ctx context.Context, iD int64) bool {
	e, err := UserLoginHistoryExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// UserLoginHistoryExists checks if the UserLoginHistory row exists.
func UserLoginHistoryExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_login_history\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if user_login_history exists")
	}

	return exists, nil
}

// Exists checks if the UserLoginHistory row exists.
func (o *UserLoginHistory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserLoginHistoryExists(ctx, exec, o.ID)
}
