// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package game_config

var TableNames = struct {
	ActionCategories          string
	ActionEffects             string
	ActionFlags               string
	ActionTypeDefinitions     string
	Actions                   string
	BuffEffects               string
	Buffs                     string
	ClassAdvancedRequirements string
	ClassAttributeBonuses     string
	ClassSkillPools           string
	Classes                   string
	DamageTypes               string
	EffectTypeDefinitions     string
	Effects                   string
	FormulaVariables          string
	HeroAttributeType         string
	RangeConfigRules          string
	SkillCategories           string
	SkillUnlockActions        string
	SkillUpgradeCosts         string
	Skills                    string
	Tags                      string
	TagsRelations             string
}{
	ActionCategories:          "action_categories",
	ActionEffects:             "action_effects",
	ActionFlags:               "action_flags",
	ActionTypeDefinitions:     "action_type_definitions",
	Actions:                   "actions",
	BuffEffects:               "buff_effects",
	Buffs:                     "buffs",
	ClassAdvancedRequirements: "class_advanced_requirements",
	ClassAttributeBonuses:     "class_attribute_bonuses",
	ClassSkillPools:           "class_skill_pools",
	Classes:                   "classes",
	DamageTypes:               "damage_types",
	EffectTypeDefinitions:     "effect_type_definitions",
	Effects:                   "effects",
	FormulaVariables:          "formula_variables",
	HeroAttributeType:         "hero_attribute_type",
	RangeConfigRules:          "range_config_rules",
	SkillCategories:           "skill_categories",
	SkillUnlockActions:        "skill_unlock_actions",
	SkillUpgradeCosts:         "skill_upgrade_costs",
	Skills:                    "skills",
	Tags:                      "tags",
	TagsRelations:             "tags_relations",
}
