// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package game_config

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// HeroLevelRequirement is an object representing the database table.
type HeroLevelRequirement struct {
	ID string `boil:"id" json:"id" toml:"id" yaml:"id"`
	// 目标等级（2-40）
	Level int `boil:"level" json:"level" toml:"level" yaml:"level"`
	// 升到该等级需要的增量经验
	RequiredXP int `boil:"required_xp" json:"required_xp" toml:"required_xp" yaml:"required_xp"`
	// 升到该等级需要的累计总经验
	CumulativeXP int       `boil:"cumulative_xp" json:"cumulative_xp" toml:"cumulative_xp" yaml:"cumulative_xp"`
	CreatedAt    null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *heroLevelRequirementR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L heroLevelRequirementL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HeroLevelRequirementColumns = struct {
	ID           string
	Level        string
	RequiredXP   string
	CumulativeXP string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	Level:        "level",
	RequiredXP:   "required_xp",
	CumulativeXP: "cumulative_xp",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var HeroLevelRequirementTableColumns = struct {
	ID           string
	Level        string
	RequiredXP   string
	CumulativeXP string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "hero_level_requirements.id",
	Level:        "hero_level_requirements.level",
	RequiredXP:   "hero_level_requirements.required_xp",
	CumulativeXP: "hero_level_requirements.cumulative_xp",
	CreatedAt:    "hero_level_requirements.created_at",
	UpdatedAt:    "hero_level_requirements.updated_at",
}

// Generated where

var HeroLevelRequirementWhere = struct {
	ID           whereHelperstring
	Level        whereHelperint
	RequiredXP   whereHelperint
	CumulativeXP whereHelperint
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"game_config\".\"hero_level_requirements\".\"id\""},
	Level:        whereHelperint{field: "\"game_config\".\"hero_level_requirements\".\"level\""},
	RequiredXP:   whereHelperint{field: "\"game_config\".\"hero_level_requirements\".\"required_xp\""},
	CumulativeXP: whereHelperint{field: "\"game_config\".\"hero_level_requirements\".\"cumulative_xp\""},
	CreatedAt:    whereHelpernull_Time{field: "\"game_config\".\"hero_level_requirements\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"game_config\".\"hero_level_requirements\".\"updated_at\""},
}

// HeroLevelRequirementRels is where relationship names are stored.
var HeroLevelRequirementRels = struct {
}{}

// heroLevelRequirementR is where relationships are stored.
type heroLevelRequirementR struct {
}

// NewStruct creates a new relationship struct
func (*heroLevelRequirementR) NewStruct() *heroLevelRequirementR {
	return &heroLevelRequirementR{}
}

// heroLevelRequirementL is where Load methods for each relationship are stored.
type heroLevelRequirementL struct{}

var (
	heroLevelRequirementAllColumns            = []string{"id", "level", "required_xp", "cumulative_xp", "created_at", "updated_at"}
	heroLevelRequirementColumnsWithoutDefault = []string{"level", "required_xp", "cumulative_xp"}
	heroLevelRequirementColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	heroLevelRequirementPrimaryKeyColumns     = []string{"id"}
	heroLevelRequirementGeneratedColumns      = []string{}
)

type (
	// HeroLevelRequirementSlice is an alias for a slice of pointers to HeroLevelRequirement.
	// This should almost always be used instead of []HeroLevelRequirement.
	HeroLevelRequirementSlice []*HeroLevelRequirement
	// HeroLevelRequirementHook is the signature for custom HeroLevelRequirement hook methods
	HeroLevelRequirementHook func(context.Context, boil.ContextExecutor, *HeroLevelRequirement) error

	heroLevelRequirementQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	heroLevelRequirementType                 = reflect.TypeOf(&HeroLevelRequirement{})
	heroLevelRequirementMapping              = queries.MakeStructMapping(heroLevelRequirementType)
	heroLevelRequirementPrimaryKeyMapping, _ = queries.BindMapping(heroLevelRequirementType, heroLevelRequirementMapping, heroLevelRequirementPrimaryKeyColumns)
	heroLevelRequirementInsertCacheMut       sync.RWMutex
	heroLevelRequirementInsertCache          = make(map[string]insertCache)
	heroLevelRequirementUpdateCacheMut       sync.RWMutex
	heroLevelRequirementUpdateCache          = make(map[string]updateCache)
	heroLevelRequirementUpsertCacheMut       sync.RWMutex
	heroLevelRequirementUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var heroLevelRequirementAfterSelectMu sync.Mutex
var heroLevelRequirementAfterSelectHooks []HeroLevelRequirementHook

var heroLevelRequirementBeforeInsertMu sync.Mutex
var heroLevelRequirementBeforeInsertHooks []HeroLevelRequirementHook
var heroLevelRequirementAfterInsertMu sync.Mutex
var heroLevelRequirementAfterInsertHooks []HeroLevelRequirementHook

var heroLevelRequirementBeforeUpdateMu sync.Mutex
var heroLevelRequirementBeforeUpdateHooks []HeroLevelRequirementHook
var heroLevelRequirementAfterUpdateMu sync.Mutex
var heroLevelRequirementAfterUpdateHooks []HeroLevelRequirementHook

var heroLevelRequirementBeforeDeleteMu sync.Mutex
var heroLevelRequirementBeforeDeleteHooks []HeroLevelRequirementHook
var heroLevelRequirementAfterDeleteMu sync.Mutex
var heroLevelRequirementAfterDeleteHooks []HeroLevelRequirementHook

var heroLevelRequirementBeforeUpsertMu sync.Mutex
var heroLevelRequirementBeforeUpsertHooks []HeroLevelRequirementHook
var heroLevelRequirementAfterUpsertMu sync.Mutex
var heroLevelRequirementAfterUpsertHooks []HeroLevelRequirementHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HeroLevelRequirement) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HeroLevelRequirement) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HeroLevelRequirement) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HeroLevelRequirement) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HeroLevelRequirement) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HeroLevelRequirement) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HeroLevelRequirement) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HeroLevelRequirement) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HeroLevelRequirement) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroLevelRequirementAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHeroLevelRequirementHook registers your hook function for all future operations.
func AddHeroLevelRequirementHook(hookPoint boil.HookPoint, heroLevelRequirementHook HeroLevelRequirementHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		heroLevelRequirementAfterSelectMu.Lock()
		heroLevelRequirementAfterSelectHooks = append(heroLevelRequirementAfterSelectHooks, heroLevelRequirementHook)
		heroLevelRequirementAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		heroLevelRequirementBeforeInsertMu.Lock()
		heroLevelRequirementBeforeInsertHooks = append(heroLevelRequirementBeforeInsertHooks, heroLevelRequirementHook)
		heroLevelRequirementBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		heroLevelRequirementAfterInsertMu.Lock()
		heroLevelRequirementAfterInsertHooks = append(heroLevelRequirementAfterInsertHooks, heroLevelRequirementHook)
		heroLevelRequirementAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		heroLevelRequirementBeforeUpdateMu.Lock()
		heroLevelRequirementBeforeUpdateHooks = append(heroLevelRequirementBeforeUpdateHooks, heroLevelRequirementHook)
		heroLevelRequirementBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		heroLevelRequirementAfterUpdateMu.Lock()
		heroLevelRequirementAfterUpdateHooks = append(heroLevelRequirementAfterUpdateHooks, heroLevelRequirementHook)
		heroLevelRequirementAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		heroLevelRequirementBeforeDeleteMu.Lock()
		heroLevelRequirementBeforeDeleteHooks = append(heroLevelRequirementBeforeDeleteHooks, heroLevelRequirementHook)
		heroLevelRequirementBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		heroLevelRequirementAfterDeleteMu.Lock()
		heroLevelRequirementAfterDeleteHooks = append(heroLevelRequirementAfterDeleteHooks, heroLevelRequirementHook)
		heroLevelRequirementAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		heroLevelRequirementBeforeUpsertMu.Lock()
		heroLevelRequirementBeforeUpsertHooks = append(heroLevelRequirementBeforeUpsertHooks, heroLevelRequirementHook)
		heroLevelRequirementBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		heroLevelRequirementAfterUpsertMu.Lock()
		heroLevelRequirementAfterUpsertHooks = append(heroLevelRequirementAfterUpsertHooks, heroLevelRequirementHook)
		heroLevelRequirementAfterUpsertMu.Unlock()
	}
}

// OneG returns a single heroLevelRequirement record from the query using the global executor.
func (q heroLevelRequirementQuery) OneG(ctx context.Context) (*HeroLevelRequirement, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single heroLevelRequirement record from the query using the global executor, and panics on error.
func (q heroLevelRequirementQuery) OneGP(ctx context.Context) *HeroLevelRequirement {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single heroLevelRequirement record from the query, and panics on error.
func (q heroLevelRequirementQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *HeroLevelRequirement {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single heroLevelRequirement record from the query.
func (q heroLevelRequirementQuery) One(ctx context.Context, exec boil.ContextExecutor) (*HeroLevelRequirement, error) {
	o := &HeroLevelRequirement{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "game_config: failed to execute a one query for hero_level_requirements")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all HeroLevelRequirement records from the query using the global executor.
func (q heroLevelRequirementQuery) AllG(ctx context.Context) (HeroLevelRequirementSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all HeroLevelRequirement records from the query using the global executor, and panics on error.
func (q heroLevelRequirementQuery) AllGP(ctx context.Context) HeroLevelRequirementSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all HeroLevelRequirement records from the query, and panics on error.
func (q heroLevelRequirementQuery) AllP(ctx context.Context, exec boil.ContextExecutor) HeroLevelRequirementSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all HeroLevelRequirement records from the query.
func (q heroLevelRequirementQuery) All(ctx context.Context, exec boil.ContextExecutor) (HeroLevelRequirementSlice, error) {
	var o []*HeroLevelRequirement

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "game_config: failed to assign all query results to HeroLevelRequirement slice")
	}

	if len(heroLevelRequirementAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all HeroLevelRequirement records in the query using the global executor
func (q heroLevelRequirementQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all HeroLevelRequirement records in the query using the global executor, and panics on error.
func (q heroLevelRequirementQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all HeroLevelRequirement records in the query, and panics on error.
func (q heroLevelRequirementQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all HeroLevelRequirement records in the query.
func (q heroLevelRequirementQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to count hero_level_requirements rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q heroLevelRequirementQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q heroLevelRequirementQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q heroLevelRequirementQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q heroLevelRequirementQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "game_config: failed to check if hero_level_requirements exists")
	}

	return count > 0, nil
}

// HeroLevelRequirements retrieves all the records using an executor.
func HeroLevelRequirements(mods ...qm.QueryMod) heroLevelRequirementQuery {
	mods = append(mods, qm.From("\"game_config\".\"hero_level_requirements\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"game_config\".\"hero_level_requirements\".*"})
	}

	return heroLevelRequirementQuery{q}
}

// FindHeroLevelRequirementG retrieves a single record by ID.
func FindHeroLevelRequirementG(ctx context.Context, iD string, selectCols ...string) (*HeroLevelRequirement, error) {
	return FindHeroLevelRequirement(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindHeroLevelRequirementP retrieves a single record by ID with an executor, and panics on error.
func FindHeroLevelRequirementP(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) *HeroLevelRequirement {
	retobj, err := FindHeroLevelRequirement(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindHeroLevelRequirementGP retrieves a single record by ID, and panics on error.
func FindHeroLevelRequirementGP(ctx context.Context, iD string, selectCols ...string) *HeroLevelRequirement {
	retobj, err := FindHeroLevelRequirement(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindHeroLevelRequirement retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHeroLevelRequirement(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*HeroLevelRequirement, error) {
	heroLevelRequirementObj := &HeroLevelRequirement{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"game_config\".\"hero_level_requirements\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, heroLevelRequirementObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "game_config: unable to select from hero_level_requirements")
	}

	if err = heroLevelRequirementObj.doAfterSelectHooks(ctx, exec); err != nil {
		return heroLevelRequirementObj, err
	}

	return heroLevelRequirementObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *HeroLevelRequirement) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *HeroLevelRequirement) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *HeroLevelRequirement) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *HeroLevelRequirement) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("game_config: no hero_level_requirements provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(heroLevelRequirementColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	heroLevelRequirementInsertCacheMut.RLock()
	cache, cached := heroLevelRequirementInsertCache[key]
	heroLevelRequirementInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			heroLevelRequirementAllColumns,
			heroLevelRequirementColumnsWithDefault,
			heroLevelRequirementColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(heroLevelRequirementType, heroLevelRequirementMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(heroLevelRequirementType, heroLevelRequirementMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"game_config\".\"hero_level_requirements\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"game_config\".\"hero_level_requirements\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "game_config: unable to insert into hero_level_requirements")
	}

	if !cached {
		heroLevelRequirementInsertCacheMut.Lock()
		heroLevelRequirementInsertCache[key] = cache
		heroLevelRequirementInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single HeroLevelRequirement record using the global executor.
// See Update for more documentation.
func (o *HeroLevelRequirement) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the HeroLevelRequirement, and panics on error.
// See Update for more documentation.
func (o *HeroLevelRequirement) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single HeroLevelRequirement record using the global executor. Panics on error.
// See Update for more documentation.
func (o *HeroLevelRequirement) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the HeroLevelRequirement.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *HeroLevelRequirement) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	heroLevelRequirementUpdateCacheMut.RLock()
	cache, cached := heroLevelRequirementUpdateCache[key]
	heroLevelRequirementUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			heroLevelRequirementAllColumns,
			heroLevelRequirementPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("game_config: unable to update hero_level_requirements, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"game_config\".\"hero_level_requirements\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, heroLevelRequirementPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(heroLevelRequirementType, heroLevelRequirementMapping, append(wl, heroLevelRequirementPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to update hero_level_requirements row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by update for hero_level_requirements")
	}

	if !cached {
		heroLevelRequirementUpdateCacheMut.Lock()
		heroLevelRequirementUpdateCache[key] = cache
		heroLevelRequirementUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q heroLevelRequirementQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q heroLevelRequirementQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q heroLevelRequirementQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q heroLevelRequirementQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to update all for hero_level_requirements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to retrieve rows affected for hero_level_requirements")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o HeroLevelRequirementSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o HeroLevelRequirementSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o HeroLevelRequirementSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HeroLevelRequirementSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("game_config: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), heroLevelRequirementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"game_config\".\"hero_level_requirements\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, heroLevelRequirementPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to update all in heroLevelRequirement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to retrieve rows affected all in update all heroLevelRequirement")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *HeroLevelRequirement) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *HeroLevelRequirement) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *HeroLevelRequirement) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *HeroLevelRequirement) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("game_config: no hero_level_requirements provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(heroLevelRequirementColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	heroLevelRequirementUpsertCacheMut.RLock()
	cache, cached := heroLevelRequirementUpsertCache[key]
	heroLevelRequirementUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			heroLevelRequirementAllColumns,
			heroLevelRequirementColumnsWithDefault,
			heroLevelRequirementColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			heroLevelRequirementAllColumns,
			heroLevelRequirementPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("game_config: unable to upsert hero_level_requirements, could not build update column list")
		}

		ret := strmangle.SetComplement(heroLevelRequirementAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(heroLevelRequirementPrimaryKeyColumns) == 0 {
				return errors.New("game_config: unable to upsert hero_level_requirements, could not build conflict column list")
			}

			conflict = make([]string, len(heroLevelRequirementPrimaryKeyColumns))
			copy(conflict, heroLevelRequirementPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"game_config\".\"hero_level_requirements\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(heroLevelRequirementType, heroLevelRequirementMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(heroLevelRequirementType, heroLevelRequirementMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "game_config: unable to upsert hero_level_requirements")
	}

	if !cached {
		heroLevelRequirementUpsertCacheMut.Lock()
		heroLevelRequirementUpsertCache[key] = cache
		heroLevelRequirementUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single HeroLevelRequirement record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *HeroLevelRequirement) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// DeleteP deletes a single HeroLevelRequirement record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *HeroLevelRequirement) DeleteP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.Delete(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single HeroLevelRequirement record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *HeroLevelRequirement) DeleteGP(ctx context.Context) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single HeroLevelRequirement record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HeroLevelRequirement) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("game_config: no HeroLevelRequirement provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), heroLevelRequirementPrimaryKeyMapping)
	sql := "DELETE FROM \"game_config\".\"hero_level_requirements\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to delete from hero_level_requirements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by delete for hero_level_requirements")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q heroLevelRequirementQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows, and panics on error.
func (q heroLevelRequirementQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q heroLevelRequirementQuery) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q heroLevelRequirementQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("game_config: no heroLevelRequirementQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to delete all from hero_level_requirements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by deleteall for hero_level_requirements")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o HeroLevelRequirementSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o HeroLevelRequirementSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o HeroLevelRequirementSlice) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HeroLevelRequirementSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(heroLevelRequirementBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), heroLevelRequirementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"game_config\".\"hero_level_requirements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, heroLevelRequirementPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to delete all from heroLevelRequirement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by deleteall for hero_level_requirements")
	}

	if len(heroLevelRequirementAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *HeroLevelRequirement) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("game_config: no HeroLevelRequirement provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *HeroLevelRequirement) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *HeroLevelRequirement) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HeroLevelRequirement) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindHeroLevelRequirement(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HeroLevelRequirementSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("game_config: empty HeroLevelRequirementSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *HeroLevelRequirementSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *HeroLevelRequirementSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HeroLevelRequirementSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HeroLevelRequirementSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), heroLevelRequirementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"game_config\".\"hero_level_requirements\".* FROM \"game_config\".\"hero_level_requirements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, heroLevelRequirementPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "game_config: unable to reload all in HeroLevelRequirementSlice")
	}

	*o = slice

	return nil
}

// HeroLevelRequirementExistsG checks if the HeroLevelRequirement row exists.
func HeroLevelRequirementExistsG(ctx context.Context, iD string) (bool, error) {
	return HeroLevelRequirementExists(ctx, boil.GetContextDB(), iD)
}

// HeroLevelRequirementExistsP checks if the HeroLevelRequirement row exists. Panics on error.
func HeroLevelRequirementExistsP(ctx context.Context, exec boil.ContextExecutor, iD string) bool {
	e, err := HeroLevelRequirementExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// HeroLevelRequirementExistsGP checks if the HeroLevelRequirement row exists. Panics on error.
func HeroLevelRequirementExistsGP(ctx context.Context, iD string) bool {
	e, err := HeroLevelRequirementExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// HeroLevelRequirementExists checks if the HeroLevelRequirement row exists.
func HeroLevelRequirementExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"game_config\".\"hero_level_requirements\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "game_config: unable to check if hero_level_requirements exists")
	}

	return exists, nil
}

// Exists checks if the HeroLevelRequirement row exists.
func (o *HeroLevelRequirement) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return HeroLevelRequirementExists(ctx, exec, o.ID)
}
