// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package game_config

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Skill is an object representing the database table.
type Skill struct {
	ID          string            `boil:"id" json:"id" toml:"id" yaml:"id"`
	SkillCode   string            `boil:"skill_code" json:"skill_code" toml:"skill_code" yaml:"skill_code"`
	SkillName   string            `boil:"skill_name" json:"skill_name" toml:"skill_name" yaml:"skill_name"`
	SkillType   string            `boil:"skill_type" json:"skill_type" toml:"skill_type" yaml:"skill_type"`
	CategoryID  null.String       `boil:"category_id" json:"category_id,omitempty" toml:"category_id" yaml:"category_id,omitempty"`
	MaxLevel    null.Int          `boil:"max_level" json:"max_level,omitempty" toml:"max_level" yaml:"max_level,omitempty"`
	FeatureTags types.StringArray `boil:"feature_tags" json:"feature_tags,omitempty" toml:"feature_tags" yaml:"feature_tags,omitempty"`
	// 被动效果配置（JSONB格式）
	PassiveEffects      null.JSON   `boil:"passive_effects" json:"passive_effects,omitempty" toml:"passive_effects" yaml:"passive_effects,omitempty"`
	Description         null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	DetailedDescription null.String `boil:"detailed_description" json:"detailed_description,omitempty" toml:"detailed_description" yaml:"detailed_description,omitempty"`
	Icon                null.String `boil:"icon" json:"icon,omitempty" toml:"icon" yaml:"icon,omitempty"`
	IsActive            null.Bool   `boil:"is_active" json:"is_active,omitempty" toml:"is_active" yaml:"is_active,omitempty"`
	CreatedAt           null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt           null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt           null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *skillR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L skillL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SkillColumns = struct {
	ID                  string
	SkillCode           string
	SkillName           string
	SkillType           string
	CategoryID          string
	MaxLevel            string
	FeatureTags         string
	PassiveEffects      string
	Description         string
	DetailedDescription string
	Icon                string
	IsActive            string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
}{
	ID:                  "id",
	SkillCode:           "skill_code",
	SkillName:           "skill_name",
	SkillType:           "skill_type",
	CategoryID:          "category_id",
	MaxLevel:            "max_level",
	FeatureTags:         "feature_tags",
	PassiveEffects:      "passive_effects",
	Description:         "description",
	DetailedDescription: "detailed_description",
	Icon:                "icon",
	IsActive:            "is_active",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	DeletedAt:           "deleted_at",
}

var SkillTableColumns = struct {
	ID                  string
	SkillCode           string
	SkillName           string
	SkillType           string
	CategoryID          string
	MaxLevel            string
	FeatureTags         string
	PassiveEffects      string
	Description         string
	DetailedDescription string
	Icon                string
	IsActive            string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
}{
	ID:                  "skills.id",
	SkillCode:           "skills.skill_code",
	SkillName:           "skills.skill_name",
	SkillType:           "skills.skill_type",
	CategoryID:          "skills.category_id",
	MaxLevel:            "skills.max_level",
	FeatureTags:         "skills.feature_tags",
	PassiveEffects:      "skills.passive_effects",
	Description:         "skills.description",
	DetailedDescription: "skills.detailed_description",
	Icon:                "skills.icon",
	IsActive:            "skills.is_active",
	CreatedAt:           "skills.created_at",
	UpdatedAt:           "skills.updated_at",
	DeletedAt:           "skills.deleted_at",
}

// Generated where

var SkillWhere = struct {
	ID                  whereHelperstring
	SkillCode           whereHelperstring
	SkillName           whereHelperstring
	SkillType           whereHelperstring
	CategoryID          whereHelpernull_String
	MaxLevel            whereHelpernull_Int
	FeatureTags         whereHelpertypes_StringArray
	PassiveEffects      whereHelpernull_JSON
	Description         whereHelpernull_String
	DetailedDescription whereHelpernull_String
	Icon                whereHelpernull_String
	IsActive            whereHelpernull_Bool
	CreatedAt           whereHelpernull_Time
	UpdatedAt           whereHelpernull_Time
	DeletedAt           whereHelpernull_Time
}{
	ID:                  whereHelperstring{field: "\"game_config\".\"skills\".\"id\""},
	SkillCode:           whereHelperstring{field: "\"game_config\".\"skills\".\"skill_code\""},
	SkillName:           whereHelperstring{field: "\"game_config\".\"skills\".\"skill_name\""},
	SkillType:           whereHelperstring{field: "\"game_config\".\"skills\".\"skill_type\""},
	CategoryID:          whereHelpernull_String{field: "\"game_config\".\"skills\".\"category_id\""},
	MaxLevel:            whereHelpernull_Int{field: "\"game_config\".\"skills\".\"max_level\""},
	FeatureTags:         whereHelpertypes_StringArray{field: "\"game_config\".\"skills\".\"feature_tags\""},
	PassiveEffects:      whereHelpernull_JSON{field: "\"game_config\".\"skills\".\"passive_effects\""},
	Description:         whereHelpernull_String{field: "\"game_config\".\"skills\".\"description\""},
	DetailedDescription: whereHelpernull_String{field: "\"game_config\".\"skills\".\"detailed_description\""},
	Icon:                whereHelpernull_String{field: "\"game_config\".\"skills\".\"icon\""},
	IsActive:            whereHelpernull_Bool{field: "\"game_config\".\"skills\".\"is_active\""},
	CreatedAt:           whereHelpernull_Time{field: "\"game_config\".\"skills\".\"created_at\""},
	UpdatedAt:           whereHelpernull_Time{field: "\"game_config\".\"skills\".\"updated_at\""},
	DeletedAt:           whereHelpernull_Time{field: "\"game_config\".\"skills\".\"deleted_at\""},
}

// SkillRels is where relationship names are stored.
var SkillRels = struct {
	Category            string
	RelatedSkillActions string
	ClassSkillPools     string
	MonsterSkills       string
	SkillUnlockActions  string
}{
	Category:            "Category",
	RelatedSkillActions: "RelatedSkillActions",
	ClassSkillPools:     "ClassSkillPools",
	MonsterSkills:       "MonsterSkills",
	SkillUnlockActions:  "SkillUnlockActions",
}

// skillR is where relationships are stored.
type skillR struct {
	Category            *SkillCategory         `boil:"Category" json:"Category" toml:"Category" yaml:"Category"`
	RelatedSkillActions ActionSlice            `boil:"RelatedSkillActions" json:"RelatedSkillActions" toml:"RelatedSkillActions" yaml:"RelatedSkillActions"`
	ClassSkillPools     ClassSkillPoolSlice    `boil:"ClassSkillPools" json:"ClassSkillPools" toml:"ClassSkillPools" yaml:"ClassSkillPools"`
	MonsterSkills       MonsterSkillSlice      `boil:"MonsterSkills" json:"MonsterSkills" toml:"MonsterSkills" yaml:"MonsterSkills"`
	SkillUnlockActions  SkillUnlockActionSlice `boil:"SkillUnlockActions" json:"SkillUnlockActions" toml:"SkillUnlockActions" yaml:"SkillUnlockActions"`
}

// NewStruct creates a new relationship struct
func (*skillR) NewStruct() *skillR {
	return &skillR{}
}

func (o *Skill) GetCategory() *SkillCategory {
	if o == nil {
		return nil
	}

	return o.R.GetCategory()
}

func (r *skillR) GetCategory() *SkillCategory {
	if r == nil {
		return nil
	}

	return r.Category
}

func (o *Skill) GetRelatedSkillActions() ActionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRelatedSkillActions()
}

func (r *skillR) GetRelatedSkillActions() ActionSlice {
	if r == nil {
		return nil
	}

	return r.RelatedSkillActions
}

func (o *Skill) GetClassSkillPools() ClassSkillPoolSlice {
	if o == nil {
		return nil
	}

	return o.R.GetClassSkillPools()
}

func (r *skillR) GetClassSkillPools() ClassSkillPoolSlice {
	if r == nil {
		return nil
	}

	return r.ClassSkillPools
}

func (o *Skill) GetMonsterSkills() MonsterSkillSlice {
	if o == nil {
		return nil
	}

	return o.R.GetMonsterSkills()
}

func (r *skillR) GetMonsterSkills() MonsterSkillSlice {
	if r == nil {
		return nil
	}

	return r.MonsterSkills
}

func (o *Skill) GetSkillUnlockActions() SkillUnlockActionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSkillUnlockActions()
}

func (r *skillR) GetSkillUnlockActions() SkillUnlockActionSlice {
	if r == nil {
		return nil
	}

	return r.SkillUnlockActions
}

// skillL is where Load methods for each relationship are stored.
type skillL struct{}

var (
	skillAllColumns            = []string{"id", "skill_code", "skill_name", "skill_type", "category_id", "max_level", "feature_tags", "passive_effects", "description", "detailed_description", "icon", "is_active", "created_at", "updated_at", "deleted_at"}
	skillColumnsWithoutDefault = []string{"skill_code", "skill_name"}
	skillColumnsWithDefault    = []string{"id", "skill_type", "category_id", "max_level", "feature_tags", "passive_effects", "description", "detailed_description", "icon", "is_active", "created_at", "updated_at", "deleted_at"}
	skillPrimaryKeyColumns     = []string{"id"}
	skillGeneratedColumns      = []string{}
)

type (
	// SkillSlice is an alias for a slice of pointers to Skill.
	// This should almost always be used instead of []Skill.
	SkillSlice []*Skill
	// SkillHook is the signature for custom Skill hook methods
	SkillHook func(context.Context, boil.ContextExecutor, *Skill) error

	skillQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	skillType                 = reflect.TypeOf(&Skill{})
	skillMapping              = queries.MakeStructMapping(skillType)
	skillPrimaryKeyMapping, _ = queries.BindMapping(skillType, skillMapping, skillPrimaryKeyColumns)
	skillInsertCacheMut       sync.RWMutex
	skillInsertCache          = make(map[string]insertCache)
	skillUpdateCacheMut       sync.RWMutex
	skillUpdateCache          = make(map[string]updateCache)
	skillUpsertCacheMut       sync.RWMutex
	skillUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var skillAfterSelectMu sync.Mutex
var skillAfterSelectHooks []SkillHook

var skillBeforeInsertMu sync.Mutex
var skillBeforeInsertHooks []SkillHook
var skillAfterInsertMu sync.Mutex
var skillAfterInsertHooks []SkillHook

var skillBeforeUpdateMu sync.Mutex
var skillBeforeUpdateHooks []SkillHook
var skillAfterUpdateMu sync.Mutex
var skillAfterUpdateHooks []SkillHook

var skillBeforeDeleteMu sync.Mutex
var skillBeforeDeleteHooks []SkillHook
var skillAfterDeleteMu sync.Mutex
var skillAfterDeleteHooks []SkillHook

var skillBeforeUpsertMu sync.Mutex
var skillBeforeUpsertHooks []SkillHook
var skillAfterUpsertMu sync.Mutex
var skillAfterUpsertHooks []SkillHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Skill) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Skill) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Skill) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Skill) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Skill) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Skill) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Skill) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Skill) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Skill) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range skillAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSkillHook registers your hook function for all future operations.
func AddSkillHook(hookPoint boil.HookPoint, skillHook SkillHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		skillAfterSelectMu.Lock()
		skillAfterSelectHooks = append(skillAfterSelectHooks, skillHook)
		skillAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		skillBeforeInsertMu.Lock()
		skillBeforeInsertHooks = append(skillBeforeInsertHooks, skillHook)
		skillBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		skillAfterInsertMu.Lock()
		skillAfterInsertHooks = append(skillAfterInsertHooks, skillHook)
		skillAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		skillBeforeUpdateMu.Lock()
		skillBeforeUpdateHooks = append(skillBeforeUpdateHooks, skillHook)
		skillBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		skillAfterUpdateMu.Lock()
		skillAfterUpdateHooks = append(skillAfterUpdateHooks, skillHook)
		skillAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		skillBeforeDeleteMu.Lock()
		skillBeforeDeleteHooks = append(skillBeforeDeleteHooks, skillHook)
		skillBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		skillAfterDeleteMu.Lock()
		skillAfterDeleteHooks = append(skillAfterDeleteHooks, skillHook)
		skillAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		skillBeforeUpsertMu.Lock()
		skillBeforeUpsertHooks = append(skillBeforeUpsertHooks, skillHook)
		skillBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		skillAfterUpsertMu.Lock()
		skillAfterUpsertHooks = append(skillAfterUpsertHooks, skillHook)
		skillAfterUpsertMu.Unlock()
	}
}

// OneG returns a single skill record from the query using the global executor.
func (q skillQuery) OneG(ctx context.Context) (*Skill, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single skill record from the query using the global executor, and panics on error.
func (q skillQuery) OneGP(ctx context.Context) *Skill {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single skill record from the query, and panics on error.
func (q skillQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *Skill {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single skill record from the query.
func (q skillQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Skill, error) {
	o := &Skill{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "game_config: failed to execute a one query for skills")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Skill records from the query using the global executor.
func (q skillQuery) AllG(ctx context.Context) (SkillSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all Skill records from the query using the global executor, and panics on error.
func (q skillQuery) AllGP(ctx context.Context) SkillSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all Skill records from the query, and panics on error.
func (q skillQuery) AllP(ctx context.Context, exec boil.ContextExecutor) SkillSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Skill records from the query.
func (q skillQuery) All(ctx context.Context, exec boil.ContextExecutor) (SkillSlice, error) {
	var o []*Skill

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "game_config: failed to assign all query results to Skill slice")
	}

	if len(skillAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Skill records in the query using the global executor
func (q skillQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all Skill records in the query using the global executor, and panics on error.
func (q skillQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all Skill records in the query, and panics on error.
func (q skillQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Skill records in the query.
func (q skillQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to count skills rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q skillQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q skillQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q skillQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q skillQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "game_config: failed to check if skills exists")
	}

	return count > 0, nil
}

// Category pointed to by the foreign key.
func (o *Skill) Category(mods ...qm.QueryMod) skillCategoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CategoryID),
	}

	queryMods = append(queryMods, mods...)

	return SkillCategories(queryMods...)
}

// RelatedSkillActions retrieves all the action's Actions with an executor via related_skill_id column.
func (o *Skill) RelatedSkillActions(mods ...qm.QueryMod) actionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"game_config\".\"actions\".\"related_skill_id\"=?", o.ID),
	)

	return Actions(queryMods...)
}

// ClassSkillPools retrieves all the class_skill_pool's ClassSkillPools with an executor.
func (o *Skill) ClassSkillPools(mods ...qm.QueryMod) classSkillPoolQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"game_config\".\"class_skill_pools\".\"skill_id\"=?", o.ID),
	)

	return ClassSkillPools(queryMods...)
}

// MonsterSkills retrieves all the monster_skill's MonsterSkills with an executor.
func (o *Skill) MonsterSkills(mods ...qm.QueryMod) monsterSkillQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"game_config\".\"monster_skills\".\"skill_id\"=?", o.ID),
	)

	return MonsterSkills(queryMods...)
}

// SkillUnlockActions retrieves all the skill_unlock_action's SkillUnlockActions with an executor.
func (o *Skill) SkillUnlockActions(mods ...qm.QueryMod) skillUnlockActionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"game_config\".\"skill_unlock_actions\".\"skill_id\"=?", o.ID),
	)

	return SkillUnlockActions(queryMods...)
}

// LoadCategory allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (skillL) LoadCategory(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSkill interface{}, mods queries.Applicator) error {
	var slice []*Skill
	var object *Skill

	if singular {
		var ok bool
		object, ok = maybeSkill.(*Skill)
		if !ok {
			object = new(Skill)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSkill))
			}
		}
	} else {
		s, ok := maybeSkill.(*[]*Skill)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSkill))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &skillR{}
		}
		if !queries.IsNil(object.CategoryID) {
			args[object.CategoryID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &skillR{}
			}

			if !queries.IsNil(obj.CategoryID) {
				args[obj.CategoryID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_config.skill_categories`),
		qm.WhereIn(`game_config.skill_categories.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_config.skill_categories.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SkillCategory")
	}

	var resultSlice []*SkillCategory
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SkillCategory")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for skill_categories")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for skill_categories")
	}

	if len(skillCategoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Category = foreign
		if foreign.R == nil {
			foreign.R = &skillCategoryR{}
		}
		foreign.R.CategorySkills = append(foreign.R.CategorySkills, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CategoryID, foreign.ID) {
				local.R.Category = foreign
				if foreign.R == nil {
					foreign.R = &skillCategoryR{}
				}
				foreign.R.CategorySkills = append(foreign.R.CategorySkills, local)
				break
			}
		}
	}

	return nil
}

// LoadRelatedSkillActions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (skillL) LoadRelatedSkillActions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSkill interface{}, mods queries.Applicator) error {
	var slice []*Skill
	var object *Skill

	if singular {
		var ok bool
		object, ok = maybeSkill.(*Skill)
		if !ok {
			object = new(Skill)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSkill))
			}
		}
	} else {
		s, ok := maybeSkill.(*[]*Skill)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSkill))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &skillR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &skillR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_config.actions`),
		qm.WhereIn(`game_config.actions.related_skill_id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_config.actions.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load actions")
	}

	var resultSlice []*Action
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice actions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on actions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for actions")
	}

	if len(actionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RelatedSkillActions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &actionR{}
			}
			foreign.R.RelatedSkill = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.RelatedSkillID) {
				local.R.RelatedSkillActions = append(local.R.RelatedSkillActions, foreign)
				if foreign.R == nil {
					foreign.R = &actionR{}
				}
				foreign.R.RelatedSkill = local
				break
			}
		}
	}

	return nil
}

// LoadClassSkillPools allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (skillL) LoadClassSkillPools(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSkill interface{}, mods queries.Applicator) error {
	var slice []*Skill
	var object *Skill

	if singular {
		var ok bool
		object, ok = maybeSkill.(*Skill)
		if !ok {
			object = new(Skill)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSkill))
			}
		}
	} else {
		s, ok := maybeSkill.(*[]*Skill)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSkill))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &skillR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &skillR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_config.class_skill_pools`),
		qm.WhereIn(`game_config.class_skill_pools.skill_id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_config.class_skill_pools.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load class_skill_pools")
	}

	var resultSlice []*ClassSkillPool
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice class_skill_pools")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on class_skill_pools")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for class_skill_pools")
	}

	if len(classSkillPoolAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ClassSkillPools = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &classSkillPoolR{}
			}
			foreign.R.Skill = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SkillID {
				local.R.ClassSkillPools = append(local.R.ClassSkillPools, foreign)
				if foreign.R == nil {
					foreign.R = &classSkillPoolR{}
				}
				foreign.R.Skill = local
				break
			}
		}
	}

	return nil
}

// LoadMonsterSkills allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (skillL) LoadMonsterSkills(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSkill interface{}, mods queries.Applicator) error {
	var slice []*Skill
	var object *Skill

	if singular {
		var ok bool
		object, ok = maybeSkill.(*Skill)
		if !ok {
			object = new(Skill)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSkill))
			}
		}
	} else {
		s, ok := maybeSkill.(*[]*Skill)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSkill))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &skillR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &skillR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_config.monster_skills`),
		qm.WhereIn(`game_config.monster_skills.skill_id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_config.monster_skills.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load monster_skills")
	}

	var resultSlice []*MonsterSkill
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice monster_skills")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on monster_skills")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for monster_skills")
	}

	if len(monsterSkillAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MonsterSkills = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &monsterSkillR{}
			}
			foreign.R.Skill = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SkillID {
				local.R.MonsterSkills = append(local.R.MonsterSkills, foreign)
				if foreign.R == nil {
					foreign.R = &monsterSkillR{}
				}
				foreign.R.Skill = local
				break
			}
		}
	}

	return nil
}

// LoadSkillUnlockActions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (skillL) LoadSkillUnlockActions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSkill interface{}, mods queries.Applicator) error {
	var slice []*Skill
	var object *Skill

	if singular {
		var ok bool
		object, ok = maybeSkill.(*Skill)
		if !ok {
			object = new(Skill)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSkill))
			}
		}
	} else {
		s, ok := maybeSkill.(*[]*Skill)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSkill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSkill))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &skillR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &skillR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_config.skill_unlock_actions`),
		qm.WhereIn(`game_config.skill_unlock_actions.skill_id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_config.skill_unlock_actions.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load skill_unlock_actions")
	}

	var resultSlice []*SkillUnlockAction
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice skill_unlock_actions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on skill_unlock_actions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for skill_unlock_actions")
	}

	if len(skillUnlockActionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SkillUnlockActions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &skillUnlockActionR{}
			}
			foreign.R.Skill = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SkillID {
				local.R.SkillUnlockActions = append(local.R.SkillUnlockActions, foreign)
				if foreign.R == nil {
					foreign.R = &skillUnlockActionR{}
				}
				foreign.R.Skill = local
				break
			}
		}
	}

	return nil
}

// SetCategoryG of the skill to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategorySkills.
// Uses the global database handle.
func (o *Skill) SetCategoryG(ctx context.Context, insert bool, related *SkillCategory) error {
	return o.SetCategory(ctx, boil.GetContextDB(), insert, related)
}

// SetCategoryP of the skill to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategorySkills.
// Panics on error.
func (o *Skill) SetCategoryP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SkillCategory) {
	if err := o.SetCategory(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCategoryGP of the skill to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategorySkills.
// Uses the global database handle and panics on error.
func (o *Skill) SetCategoryGP(ctx context.Context, insert bool, related *SkillCategory) {
	if err := o.SetCategory(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCategory of the skill to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategorySkills.
func (o *Skill) SetCategory(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SkillCategory) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"game_config\".\"skills\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"category_id"}),
		strmangle.WhereClause("\"", "\"", 2, skillPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CategoryID, related.ID)
	if o.R == nil {
		o.R = &skillR{
			Category: related,
		}
	} else {
		o.R.Category = related
	}

	if related.R == nil {
		related.R = &skillCategoryR{
			CategorySkills: SkillSlice{o},
		}
	} else {
		related.R.CategorySkills = append(related.R.CategorySkills, o)
	}

	return nil
}

// RemoveCategoryG relationship.
// Sets o.R.Category to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *Skill) RemoveCategoryG(ctx context.Context, related *SkillCategory) error {
	return o.RemoveCategory(ctx, boil.GetContextDB(), related)
}

// RemoveCategoryP relationship.
// Sets o.R.Category to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *Skill) RemoveCategoryP(ctx context.Context, exec boil.ContextExecutor, related *SkillCategory) {
	if err := o.RemoveCategory(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveCategoryGP relationship.
// Sets o.R.Category to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *Skill) RemoveCategoryGP(ctx context.Context, related *SkillCategory) {
	if err := o.RemoveCategory(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveCategory relationship.
// Sets o.R.Category to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Skill) RemoveCategory(ctx context.Context, exec boil.ContextExecutor, related *SkillCategory) error {
	var err error

	queries.SetScanner(&o.CategoryID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("category_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Category = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.CategorySkills {
		if queries.Equal(o.CategoryID, ri.CategoryID) {
			continue
		}

		ln := len(related.R.CategorySkills)
		if ln > 1 && i < ln-1 {
			related.R.CategorySkills[i] = related.R.CategorySkills[ln-1]
		}
		related.R.CategorySkills = related.R.CategorySkills[:ln-1]
		break
	}
	return nil
}

// AddRelatedSkillActionsG adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.RelatedSkillActions.
// Sets related.R.RelatedSkill appropriately.
// Uses the global database handle.
func (o *Skill) AddRelatedSkillActionsG(ctx context.Context, insert bool, related ...*Action) error {
	return o.AddRelatedSkillActions(ctx, boil.GetContextDB(), insert, related...)
}

// AddRelatedSkillActionsP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.RelatedSkillActions.
// Sets related.R.RelatedSkill appropriately.
// Panics on error.
func (o *Skill) AddRelatedSkillActionsP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Action) {
	if err := o.AddRelatedSkillActions(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddRelatedSkillActionsGP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.RelatedSkillActions.
// Sets related.R.RelatedSkill appropriately.
// Uses the global database handle and panics on error.
func (o *Skill) AddRelatedSkillActionsGP(ctx context.Context, insert bool, related ...*Action) {
	if err := o.AddRelatedSkillActions(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddRelatedSkillActions adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.RelatedSkillActions.
// Sets related.R.RelatedSkill appropriately.
func (o *Skill) AddRelatedSkillActions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Action) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.RelatedSkillID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"game_config\".\"actions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"related_skill_id"}),
				strmangle.WhereClause("\"", "\"", 2, actionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.RelatedSkillID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &skillR{
			RelatedSkillActions: related,
		}
	} else {
		o.R.RelatedSkillActions = append(o.R.RelatedSkillActions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &actionR{
				RelatedSkill: o,
			}
		} else {
			rel.R.RelatedSkill = o
		}
	}
	return nil
}

// SetRelatedSkillActionsG removes all previously related items of the
// skill replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RelatedSkill's RelatedSkillActions accordingly.
// Replaces o.R.RelatedSkillActions with related.
// Sets related.R.RelatedSkill's RelatedSkillActions accordingly.
// Uses the global database handle.
func (o *Skill) SetRelatedSkillActionsG(ctx context.Context, insert bool, related ...*Action) error {
	return o.SetRelatedSkillActions(ctx, boil.GetContextDB(), insert, related...)
}

// SetRelatedSkillActionsP removes all previously related items of the
// skill replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RelatedSkill's RelatedSkillActions accordingly.
// Replaces o.R.RelatedSkillActions with related.
// Sets related.R.RelatedSkill's RelatedSkillActions accordingly.
// Panics on error.
func (o *Skill) SetRelatedSkillActionsP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Action) {
	if err := o.SetRelatedSkillActions(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetRelatedSkillActionsGP removes all previously related items of the
// skill replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RelatedSkill's RelatedSkillActions accordingly.
// Replaces o.R.RelatedSkillActions with related.
// Sets related.R.RelatedSkill's RelatedSkillActions accordingly.
// Uses the global database handle and panics on error.
func (o *Skill) SetRelatedSkillActionsGP(ctx context.Context, insert bool, related ...*Action) {
	if err := o.SetRelatedSkillActions(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetRelatedSkillActions removes all previously related items of the
// skill replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RelatedSkill's RelatedSkillActions accordingly.
// Replaces o.R.RelatedSkillActions with related.
// Sets related.R.RelatedSkill's RelatedSkillActions accordingly.
func (o *Skill) SetRelatedSkillActions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Action) error {
	query := "update \"game_config\".\"actions\" set \"related_skill_id\" = null where \"related_skill_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.RelatedSkillActions {
			queries.SetScanner(&rel.RelatedSkillID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.RelatedSkill = nil
		}
		o.R.RelatedSkillActions = nil
	}

	return o.AddRelatedSkillActions(ctx, exec, insert, related...)
}

// RemoveRelatedSkillActionsG relationships from objects passed in.
// Removes related items from R.RelatedSkillActions (uses pointer comparison, removal does not keep order)
// Sets related.R.RelatedSkill.
// Uses the global database handle.
func (o *Skill) RemoveRelatedSkillActionsG(ctx context.Context, related ...*Action) error {
	return o.RemoveRelatedSkillActions(ctx, boil.GetContextDB(), related...)
}

// RemoveRelatedSkillActionsP relationships from objects passed in.
// Removes related items from R.RelatedSkillActions (uses pointer comparison, removal does not keep order)
// Sets related.R.RelatedSkill.
// Panics on error.
func (o *Skill) RemoveRelatedSkillActionsP(ctx context.Context, exec boil.ContextExecutor, related ...*Action) {
	if err := o.RemoveRelatedSkillActions(ctx, exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveRelatedSkillActionsGP relationships from objects passed in.
// Removes related items from R.RelatedSkillActions (uses pointer comparison, removal does not keep order)
// Sets related.R.RelatedSkill.
// Uses the global database handle and panics on error.
func (o *Skill) RemoveRelatedSkillActionsGP(ctx context.Context, related ...*Action) {
	if err := o.RemoveRelatedSkillActions(ctx, boil.GetContextDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveRelatedSkillActions relationships from objects passed in.
// Removes related items from R.RelatedSkillActions (uses pointer comparison, removal does not keep order)
// Sets related.R.RelatedSkill.
func (o *Skill) RemoveRelatedSkillActions(ctx context.Context, exec boil.ContextExecutor, related ...*Action) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.RelatedSkillID, nil)
		if rel.R != nil {
			rel.R.RelatedSkill = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("related_skill_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.RelatedSkillActions {
			if rel != ri {
				continue
			}

			ln := len(o.R.RelatedSkillActions)
			if ln > 1 && i < ln-1 {
				o.R.RelatedSkillActions[i] = o.R.RelatedSkillActions[ln-1]
			}
			o.R.RelatedSkillActions = o.R.RelatedSkillActions[:ln-1]
			break
		}
	}

	return nil
}

// AddClassSkillPoolsG adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.ClassSkillPools.
// Sets related.R.Skill appropriately.
// Uses the global database handle.
func (o *Skill) AddClassSkillPoolsG(ctx context.Context, insert bool, related ...*ClassSkillPool) error {
	return o.AddClassSkillPools(ctx, boil.GetContextDB(), insert, related...)
}

// AddClassSkillPoolsP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.ClassSkillPools.
// Sets related.R.Skill appropriately.
// Panics on error.
func (o *Skill) AddClassSkillPoolsP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ClassSkillPool) {
	if err := o.AddClassSkillPools(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddClassSkillPoolsGP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.ClassSkillPools.
// Sets related.R.Skill appropriately.
// Uses the global database handle and panics on error.
func (o *Skill) AddClassSkillPoolsGP(ctx context.Context, insert bool, related ...*ClassSkillPool) {
	if err := o.AddClassSkillPools(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddClassSkillPools adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.ClassSkillPools.
// Sets related.R.Skill appropriately.
func (o *Skill) AddClassSkillPools(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ClassSkillPool) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SkillID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"game_config\".\"class_skill_pools\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"skill_id"}),
				strmangle.WhereClause("\"", "\"", 2, classSkillPoolPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SkillID = o.ID
		}
	}

	if o.R == nil {
		o.R = &skillR{
			ClassSkillPools: related,
		}
	} else {
		o.R.ClassSkillPools = append(o.R.ClassSkillPools, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &classSkillPoolR{
				Skill: o,
			}
		} else {
			rel.R.Skill = o
		}
	}
	return nil
}

// AddMonsterSkillsG adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.MonsterSkills.
// Sets related.R.Skill appropriately.
// Uses the global database handle.
func (o *Skill) AddMonsterSkillsG(ctx context.Context, insert bool, related ...*MonsterSkill) error {
	return o.AddMonsterSkills(ctx, boil.GetContextDB(), insert, related...)
}

// AddMonsterSkillsP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.MonsterSkills.
// Sets related.R.Skill appropriately.
// Panics on error.
func (o *Skill) AddMonsterSkillsP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MonsterSkill) {
	if err := o.AddMonsterSkills(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMonsterSkillsGP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.MonsterSkills.
// Sets related.R.Skill appropriately.
// Uses the global database handle and panics on error.
func (o *Skill) AddMonsterSkillsGP(ctx context.Context, insert bool, related ...*MonsterSkill) {
	if err := o.AddMonsterSkills(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddMonsterSkills adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.MonsterSkills.
// Sets related.R.Skill appropriately.
func (o *Skill) AddMonsterSkills(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MonsterSkill) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SkillID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"game_config\".\"monster_skills\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"skill_id"}),
				strmangle.WhereClause("\"", "\"", 2, monsterSkillPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SkillID = o.ID
		}
	}

	if o.R == nil {
		o.R = &skillR{
			MonsterSkills: related,
		}
	} else {
		o.R.MonsterSkills = append(o.R.MonsterSkills, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &monsterSkillR{
				Skill: o,
			}
		} else {
			rel.R.Skill = o
		}
	}
	return nil
}

// AddSkillUnlockActionsG adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.SkillUnlockActions.
// Sets related.R.Skill appropriately.
// Uses the global database handle.
func (o *Skill) AddSkillUnlockActionsG(ctx context.Context, insert bool, related ...*SkillUnlockAction) error {
	return o.AddSkillUnlockActions(ctx, boil.GetContextDB(), insert, related...)
}

// AddSkillUnlockActionsP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.SkillUnlockActions.
// Sets related.R.Skill appropriately.
// Panics on error.
func (o *Skill) AddSkillUnlockActionsP(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SkillUnlockAction) {
	if err := o.AddSkillUnlockActions(ctx, exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSkillUnlockActionsGP adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.SkillUnlockActions.
// Sets related.R.Skill appropriately.
// Uses the global database handle and panics on error.
func (o *Skill) AddSkillUnlockActionsGP(ctx context.Context, insert bool, related ...*SkillUnlockAction) {
	if err := o.AddSkillUnlockActions(ctx, boil.GetContextDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddSkillUnlockActions adds the given related objects to the existing relationships
// of the skill, optionally inserting them as new records.
// Appends related to o.R.SkillUnlockActions.
// Sets related.R.Skill appropriately.
func (o *Skill) AddSkillUnlockActions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SkillUnlockAction) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SkillID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"game_config\".\"skill_unlock_actions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"skill_id"}),
				strmangle.WhereClause("\"", "\"", 2, skillUnlockActionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SkillID = o.ID
		}
	}

	if o.R == nil {
		o.R = &skillR{
			SkillUnlockActions: related,
		}
	} else {
		o.R.SkillUnlockActions = append(o.R.SkillUnlockActions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &skillUnlockActionR{
				Skill: o,
			}
		} else {
			rel.R.Skill = o
		}
	}
	return nil
}

// Skills retrieves all the records using an executor.
func Skills(mods ...qm.QueryMod) skillQuery {
	mods = append(mods, qm.From("\"game_config\".\"skills\""), qmhelper.WhereIsNull("\"game_config\".\"skills\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"game_config\".\"skills\".*"})
	}

	return skillQuery{q}
}

// FindSkillG retrieves a single record by ID.
func FindSkillG(ctx context.Context, iD string, selectCols ...string) (*Skill, error) {
	return FindSkill(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindSkillP retrieves a single record by ID with an executor, and panics on error.
func FindSkillP(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) *Skill {
	retobj, err := FindSkill(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindSkillGP retrieves a single record by ID, and panics on error.
func FindSkillGP(ctx context.Context, iD string, selectCols ...string) *Skill {
	retobj, err := FindSkill(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindSkill retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSkill(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Skill, error) {
	skillObj := &Skill{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"game_config\".\"skills\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, skillObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "game_config: unable to select from skills")
	}

	if err = skillObj.doAfterSelectHooks(ctx, exec); err != nil {
		return skillObj, err
	}

	return skillObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Skill) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Skill) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Skill) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Skill) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("game_config: no skills provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(skillColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	skillInsertCacheMut.RLock()
	cache, cached := skillInsertCache[key]
	skillInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			skillAllColumns,
			skillColumnsWithDefault,
			skillColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(skillType, skillMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(skillType, skillMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"game_config\".\"skills\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"game_config\".\"skills\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "game_config: unable to insert into skills")
	}

	if !cached {
		skillInsertCacheMut.Lock()
		skillInsertCache[key] = cache
		skillInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Skill record using the global executor.
// See Update for more documentation.
func (o *Skill) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the Skill, and panics on error.
// See Update for more documentation.
func (o *Skill) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single Skill record using the global executor. Panics on error.
// See Update for more documentation.
func (o *Skill) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the Skill.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Skill) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	skillUpdateCacheMut.RLock()
	cache, cached := skillUpdateCache[key]
	skillUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			skillAllColumns,
			skillPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("game_config: unable to update skills, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"game_config\".\"skills\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, skillPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(skillType, skillMapping, append(wl, skillPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to update skills row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by update for skills")
	}

	if !cached {
		skillUpdateCacheMut.Lock()
		skillUpdateCache[key] = cache
		skillUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q skillQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q skillQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q skillQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q skillQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to update all for skills")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to retrieve rows affected for skills")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o SkillSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o SkillSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o SkillSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SkillSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("game_config: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), skillPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"game_config\".\"skills\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, skillPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to update all in skill slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to retrieve rows affected all in update all skill")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Skill) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Skill) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Skill) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Skill) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("game_config: no skills provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(skillColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	skillUpsertCacheMut.RLock()
	cache, cached := skillUpsertCache[key]
	skillUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			skillAllColumns,
			skillColumnsWithDefault,
			skillColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			skillAllColumns,
			skillPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("game_config: unable to upsert skills, could not build update column list")
		}

		ret := strmangle.SetComplement(skillAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(skillPrimaryKeyColumns) == 0 {
				return errors.New("game_config: unable to upsert skills, could not build conflict column list")
			}

			conflict = make([]string, len(skillPrimaryKeyColumns))
			copy(conflict, skillPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"game_config\".\"skills\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(skillType, skillMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(skillType, skillMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "game_config: unable to upsert skills")
	}

	if !cached {
		skillUpsertCacheMut.Lock()
		skillUpsertCache[key] = cache
		skillUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Skill record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Skill) DeleteG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteP deletes a single Skill record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Skill) DeleteP(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) int64 {
	rowsAff, err := o.Delete(ctx, exec, hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single Skill record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Skill) DeleteGP(ctx context.Context, hardDelete bool) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB(), hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single Skill record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Skill) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("game_config: no Skill provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), skillPrimaryKeyMapping)
		sql = "DELETE FROM \"game_config\".\"skills\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"game_config\".\"skills\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(skillType, skillMapping, append(wl, skillPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to delete from skills")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by delete for skills")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q skillQuery) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAllP deletes all rows, and panics on error.
func (q skillQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec, hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q skillQuery) DeleteAllGP(ctx context.Context, hardDelete bool) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q skillQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("game_config: no skillQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to delete all from skills")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by deleteall for skills")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o SkillSlice) DeleteAllG(ctx context.Context, hardDelete bool) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o SkillSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec, hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o SkillSlice) DeleteAllGP(ctx context.Context, hardDelete bool) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB(), hardDelete)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SkillSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(skillBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), skillPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"game_config\".\"skills\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, skillPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), skillPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"game_config\".\"skills\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, skillPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_config: unable to delete all from skill slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_config: failed to get rows affected by deleteall for skills")
	}

	if len(skillAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Skill) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("game_config: no Skill provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Skill) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Skill) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Skill) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSkill(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SkillSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("game_config: empty SkillSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SkillSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SkillSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SkillSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SkillSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), skillPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"game_config\".\"skills\".* FROM \"game_config\".\"skills\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, skillPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "game_config: unable to reload all in SkillSlice")
	}

	*o = slice

	return nil
}

// SkillExistsG checks if the Skill row exists.
func SkillExistsG(ctx context.Context, iD string) (bool, error) {
	return SkillExists(ctx, boil.GetContextDB(), iD)
}

// SkillExistsP checks if the Skill row exists. Panics on error.
func SkillExistsP(ctx context.Context, exec boil.ContextExecutor, iD string) bool {
	e, err := SkillExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// SkillExistsGP checks if the Skill row exists. Panics on error.
func SkillExistsGP(ctx context.Context, iD string) bool {
	e, err := SkillExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// SkillExists checks if the Skill row exists.
func SkillExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"game_config\".\"skills\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "game_config: unable to check if skills exists")
	}

	return exists, nil
}

// Exists checks if the Skill row exists.
func (o *Skill) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SkillExists(ctx, exec, o.ID)
}
