FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# 复制所有源代码
COPY . .

WORKDIR /app/cmd/admin

RUN CGO_ENABLED=0 go build -o /bin/admin .

FROM alpine:latest
COPY --from=builder /bin/admin /bin/admin

EXPOSE 8080
CMD [ "/bin/admin" ]