FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# 复制所有源代码
COPY . .

WORKDIR /app/cmd/login_shim

RUN CGO_ENABLED=0 go build -o /bin/login_shim .

FROM alpine:latest
COPY --from=builder /bin/login_shim /bin/login_shim

EXPOSE 8090
CMD [ "/bin/login_shim" ]