# ==========================================
# ORY Kratos 生产环境配置
# ==========================================

version: v1.3.1

serve:
  public:
    base_url: http://47.239.139.109:4433/
    host: 0.0.0.0
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - http://47.239.139.109
        - http://47.239.139.109:80
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
  admin:
    host: 0.0.0.0
    port: 4434

# DSN 从环境变量读取
# DSN: postgres://ory_user:password@tsu_postgres_ory:5432/ory_db?sslmode=disable&search_path=kratos

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: "http://47.239.139.109/user/dashboard"
  allowed_return_urls:
    - "http://47.239.139.109"
    - "http://47.239.139.109/user/dashboard"
    - "http://47.239.139.109/user/login"
  flows:
    error:
      ui_url: "http://47.239.139.109/user/error"
    login:
      ui_url: "http://47.239.139.109/user/login"
      lifespan: 10m
    registration:
      ui_url: "http://47.239.139.109/user/registration"
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session
    recovery:
      enabled: true
      use: code  # 使用验证码模式（支持 API 模式）
      lifespan: 1h
      notify_unknown_recipients: false
      ui_url: "http://47.239.139.109/user/recovery"
      after:
        default_browser_return_url: "http://47.239.139.109/user/login"
    verification:
      ui_url: "http://47.239.139.109/user/verification"
      enabled: true
    settings:
      ui_url: "http://47.239.139.109/user/settings"
      privileged_session_max_age: 15m
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
        min_password_length: 6
        max_breaches: 0
    profile:
      enabled: true
    code:
      enabled: true  # 启用验证码方法
      config:
        lifespan: 15m  # 验证码有效期
    webauthn:
      enabled: false
    totp:
      enabled: false

session:
  cookie:
    name: ory_kratos_session
    path: /
    domain: 47.239.139.109
    same_site: Lax
    persistent: true
  lifespan: 24h
  earliest_possible_extend: 1h
  whoami:
    required_aal: aal1

# Feature Flags - 启用 Native App 支持
feature_flags:
  use_continue_with_transitions: true  # 启用 API 模式

# Secrets 从环境变量读取
# secrets:
#   cookie:
#     - ${SECRETS_COOKIE}
#   cipher:
#     - ${SECRETS_CIPHER}

log:
  level: info
  format: json
  leak_sensitive_values: false

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 12

# Courier 邮件服务配置
courier:
  smtp:
    connection_uri: smtps://1902104816@qq.com:jxlumrydpmiocfdj@smtp.qq.com:465/?skip_ssl_verify=false
    from_address: 1902104816@qq.com
    from_name: TSU Game Platform
