// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package game_runtime

var TableNames = struct {
	HeroAllocatedAttributes string
	HeroAttributeOperations string
	HeroClassHistory        string
	HeroEquipmentSlots      string
	HeroSkillOperations     string
	HeroSkills              string
	Heroes                  string
	ItemDropRecords         string
	ItemOperationLogs       string
	PlayerItems             string
	TeamDungeonProgress     string
	TeamDungeonRecords      string
	WorldDropStats          string
}{
	HeroAllocatedAttributes: "hero_allocated_attributes",
	HeroAttributeOperations: "hero_attribute_operations",
	HeroClassHistory:        "hero_class_history",
	HeroEquipmentSlots:      "hero_equipment_slots",
	HeroSkillOperations:     "hero_skill_operations",
	HeroSkills:              "hero_skills",
	Heroes:                  "heroes",
	ItemDropRecords:         "item_drop_records",
	ItemOperationLogs:       "item_operation_logs",
	PlayerItems:             "player_items",
	TeamDungeonProgress:     "team_dungeon_progress",
	TeamDungeonRecords:      "team_dungeon_records",
	WorldDropStats:          "world_drop_stats",
}
