// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package game_runtime

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// HeroEquipmentSlot is an object representing the database table.
type HeroEquipmentSlot struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	HeroID         string      `boil:"hero_id" json:"hero_id" toml:"hero_id" yaml:"hero_id"`
	SlotType       string      `boil:"slot_type" json:"slot_type" toml:"slot_type" yaml:"slot_type"`
	SlotIndex      int16       `boil:"slot_index" json:"slot_index" toml:"slot_index" yaml:"slot_index"`
	EquippedItemID null.String `boil:"equipped_item_id" json:"equipped_item_id,omitempty" toml:"equipped_item_id" yaml:"equipped_item_id,omitempty"`
	IsUnlocked     bool        `boil:"is_unlocked" json:"is_unlocked" toml:"is_unlocked" yaml:"is_unlocked"`
	UnlockLevel    null.Int16  `boil:"unlock_level" json:"unlock_level,omitempty" toml:"unlock_level" yaml:"unlock_level,omitempty"`
	// 由哪个装备增加的槽位 - 如果是装备效果增加的槽位,记录装备ID,卸下装备时删除槽位
	AddedByItemID null.String `boil:"added_by_item_id" json:"added_by_item_id,omitempty" toml:"added_by_item_id" yaml:"added_by_item_id,omitempty"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *heroEquipmentSlotR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L heroEquipmentSlotL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HeroEquipmentSlotColumns = struct {
	ID             string
	HeroID         string
	SlotType       string
	SlotIndex      string
	EquippedItemID string
	IsUnlocked     string
	UnlockLevel    string
	AddedByItemID  string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	HeroID:         "hero_id",
	SlotType:       "slot_type",
	SlotIndex:      "slot_index",
	EquippedItemID: "equipped_item_id",
	IsUnlocked:     "is_unlocked",
	UnlockLevel:    "unlock_level",
	AddedByItemID:  "added_by_item_id",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var HeroEquipmentSlotTableColumns = struct {
	ID             string
	HeroID         string
	SlotType       string
	SlotIndex      string
	EquippedItemID string
	IsUnlocked     string
	UnlockLevel    string
	AddedByItemID  string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "hero_equipment_slots.id",
	HeroID:         "hero_equipment_slots.hero_id",
	SlotType:       "hero_equipment_slots.slot_type",
	SlotIndex:      "hero_equipment_slots.slot_index",
	EquippedItemID: "hero_equipment_slots.equipped_item_id",
	IsUnlocked:     "hero_equipment_slots.is_unlocked",
	UnlockLevel:    "hero_equipment_slots.unlock_level",
	AddedByItemID:  "hero_equipment_slots.added_by_item_id",
	CreatedAt:      "hero_equipment_slots.created_at",
	UpdatedAt:      "hero_equipment_slots.updated_at",
}

// Generated where

type whereHelperint16 struct{ field string }

func (w whereHelperint16) EQ(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint16) NEQ(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint16) LT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint16) LTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint16) GT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint16) GTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint16) IN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint16) NIN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Int16 struct{ field string }

func (w whereHelpernull_Int16) EQ(x null.Int16) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int16) NEQ(x null.Int16) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int16) LT(x null.Int16) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int16) LTE(x null.Int16) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int16) GT(x null.Int16) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int16) GTE(x null.Int16) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int16) IN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int16) NIN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int16) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int16) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var HeroEquipmentSlotWhere = struct {
	ID             whereHelperstring
	HeroID         whereHelperstring
	SlotType       whereHelperstring
	SlotIndex      whereHelperint16
	EquippedItemID whereHelpernull_String
	IsUnlocked     whereHelperbool
	UnlockLevel    whereHelpernull_Int16
	AddedByItemID  whereHelpernull_String
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperstring{field: "\"game_runtime\".\"hero_equipment_slots\".\"id\""},
	HeroID:         whereHelperstring{field: "\"game_runtime\".\"hero_equipment_slots\".\"hero_id\""},
	SlotType:       whereHelperstring{field: "\"game_runtime\".\"hero_equipment_slots\".\"slot_type\""},
	SlotIndex:      whereHelperint16{field: "\"game_runtime\".\"hero_equipment_slots\".\"slot_index\""},
	EquippedItemID: whereHelpernull_String{field: "\"game_runtime\".\"hero_equipment_slots\".\"equipped_item_id\""},
	IsUnlocked:     whereHelperbool{field: "\"game_runtime\".\"hero_equipment_slots\".\"is_unlocked\""},
	UnlockLevel:    whereHelpernull_Int16{field: "\"game_runtime\".\"hero_equipment_slots\".\"unlock_level\""},
	AddedByItemID:  whereHelpernull_String{field: "\"game_runtime\".\"hero_equipment_slots\".\"added_by_item_id\""},
	CreatedAt:      whereHelpertime_Time{field: "\"game_runtime\".\"hero_equipment_slots\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"game_runtime\".\"hero_equipment_slots\".\"updated_at\""},
}

// HeroEquipmentSlotRels is where relationship names are stored.
var HeroEquipmentSlotRels = struct {
	AddedByItem  string
	EquippedItem string
	Hero         string
}{
	AddedByItem:  "AddedByItem",
	EquippedItem: "EquippedItem",
	Hero:         "Hero",
}

// heroEquipmentSlotR is where relationships are stored.
type heroEquipmentSlotR struct {
	AddedByItem  *PlayerItem `boil:"AddedByItem" json:"AddedByItem" toml:"AddedByItem" yaml:"AddedByItem"`
	EquippedItem *PlayerItem `boil:"EquippedItem" json:"EquippedItem" toml:"EquippedItem" yaml:"EquippedItem"`
	Hero         *Hero       `boil:"Hero" json:"Hero" toml:"Hero" yaml:"Hero"`
}

// NewStruct creates a new relationship struct
func (*heroEquipmentSlotR) NewStruct() *heroEquipmentSlotR {
	return &heroEquipmentSlotR{}
}

func (o *HeroEquipmentSlot) GetAddedByItem() *PlayerItem {
	if o == nil {
		return nil
	}

	return o.R.GetAddedByItem()
}

func (r *heroEquipmentSlotR) GetAddedByItem() *PlayerItem {
	if r == nil {
		return nil
	}

	return r.AddedByItem
}

func (o *HeroEquipmentSlot) GetEquippedItem() *PlayerItem {
	if o == nil {
		return nil
	}

	return o.R.GetEquippedItem()
}

func (r *heroEquipmentSlotR) GetEquippedItem() *PlayerItem {
	if r == nil {
		return nil
	}

	return r.EquippedItem
}

func (o *HeroEquipmentSlot) GetHero() *Hero {
	if o == nil {
		return nil
	}

	return o.R.GetHero()
}

func (r *heroEquipmentSlotR) GetHero() *Hero {
	if r == nil {
		return nil
	}

	return r.Hero
}

// heroEquipmentSlotL is where Load methods for each relationship are stored.
type heroEquipmentSlotL struct{}

var (
	heroEquipmentSlotAllColumns            = []string{"id", "hero_id", "slot_type", "slot_index", "equipped_item_id", "is_unlocked", "unlock_level", "added_by_item_id", "created_at", "updated_at"}
	heroEquipmentSlotColumnsWithoutDefault = []string{"hero_id", "slot_type"}
	heroEquipmentSlotColumnsWithDefault    = []string{"id", "slot_index", "equipped_item_id", "is_unlocked", "unlock_level", "added_by_item_id", "created_at", "updated_at"}
	heroEquipmentSlotPrimaryKeyColumns     = []string{"id"}
	heroEquipmentSlotGeneratedColumns      = []string{}
)

type (
	// HeroEquipmentSlotSlice is an alias for a slice of pointers to HeroEquipmentSlot.
	// This should almost always be used instead of []HeroEquipmentSlot.
	HeroEquipmentSlotSlice []*HeroEquipmentSlot
	// HeroEquipmentSlotHook is the signature for custom HeroEquipmentSlot hook methods
	HeroEquipmentSlotHook func(context.Context, boil.ContextExecutor, *HeroEquipmentSlot) error

	heroEquipmentSlotQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	heroEquipmentSlotType                 = reflect.TypeOf(&HeroEquipmentSlot{})
	heroEquipmentSlotMapping              = queries.MakeStructMapping(heroEquipmentSlotType)
	heroEquipmentSlotPrimaryKeyMapping, _ = queries.BindMapping(heroEquipmentSlotType, heroEquipmentSlotMapping, heroEquipmentSlotPrimaryKeyColumns)
	heroEquipmentSlotInsertCacheMut       sync.RWMutex
	heroEquipmentSlotInsertCache          = make(map[string]insertCache)
	heroEquipmentSlotUpdateCacheMut       sync.RWMutex
	heroEquipmentSlotUpdateCache          = make(map[string]updateCache)
	heroEquipmentSlotUpsertCacheMut       sync.RWMutex
	heroEquipmentSlotUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var heroEquipmentSlotAfterSelectMu sync.Mutex
var heroEquipmentSlotAfterSelectHooks []HeroEquipmentSlotHook

var heroEquipmentSlotBeforeInsertMu sync.Mutex
var heroEquipmentSlotBeforeInsertHooks []HeroEquipmentSlotHook
var heroEquipmentSlotAfterInsertMu sync.Mutex
var heroEquipmentSlotAfterInsertHooks []HeroEquipmentSlotHook

var heroEquipmentSlotBeforeUpdateMu sync.Mutex
var heroEquipmentSlotBeforeUpdateHooks []HeroEquipmentSlotHook
var heroEquipmentSlotAfterUpdateMu sync.Mutex
var heroEquipmentSlotAfterUpdateHooks []HeroEquipmentSlotHook

var heroEquipmentSlotBeforeDeleteMu sync.Mutex
var heroEquipmentSlotBeforeDeleteHooks []HeroEquipmentSlotHook
var heroEquipmentSlotAfterDeleteMu sync.Mutex
var heroEquipmentSlotAfterDeleteHooks []HeroEquipmentSlotHook

var heroEquipmentSlotBeforeUpsertMu sync.Mutex
var heroEquipmentSlotBeforeUpsertHooks []HeroEquipmentSlotHook
var heroEquipmentSlotAfterUpsertMu sync.Mutex
var heroEquipmentSlotAfterUpsertHooks []HeroEquipmentSlotHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HeroEquipmentSlot) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HeroEquipmentSlot) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HeroEquipmentSlot) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HeroEquipmentSlot) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HeroEquipmentSlot) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HeroEquipmentSlot) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HeroEquipmentSlot) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HeroEquipmentSlot) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HeroEquipmentSlot) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range heroEquipmentSlotAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHeroEquipmentSlotHook registers your hook function for all future operations.
func AddHeroEquipmentSlotHook(hookPoint boil.HookPoint, heroEquipmentSlotHook HeroEquipmentSlotHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		heroEquipmentSlotAfterSelectMu.Lock()
		heroEquipmentSlotAfterSelectHooks = append(heroEquipmentSlotAfterSelectHooks, heroEquipmentSlotHook)
		heroEquipmentSlotAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		heroEquipmentSlotBeforeInsertMu.Lock()
		heroEquipmentSlotBeforeInsertHooks = append(heroEquipmentSlotBeforeInsertHooks, heroEquipmentSlotHook)
		heroEquipmentSlotBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		heroEquipmentSlotAfterInsertMu.Lock()
		heroEquipmentSlotAfterInsertHooks = append(heroEquipmentSlotAfterInsertHooks, heroEquipmentSlotHook)
		heroEquipmentSlotAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		heroEquipmentSlotBeforeUpdateMu.Lock()
		heroEquipmentSlotBeforeUpdateHooks = append(heroEquipmentSlotBeforeUpdateHooks, heroEquipmentSlotHook)
		heroEquipmentSlotBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		heroEquipmentSlotAfterUpdateMu.Lock()
		heroEquipmentSlotAfterUpdateHooks = append(heroEquipmentSlotAfterUpdateHooks, heroEquipmentSlotHook)
		heroEquipmentSlotAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		heroEquipmentSlotBeforeDeleteMu.Lock()
		heroEquipmentSlotBeforeDeleteHooks = append(heroEquipmentSlotBeforeDeleteHooks, heroEquipmentSlotHook)
		heroEquipmentSlotBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		heroEquipmentSlotAfterDeleteMu.Lock()
		heroEquipmentSlotAfterDeleteHooks = append(heroEquipmentSlotAfterDeleteHooks, heroEquipmentSlotHook)
		heroEquipmentSlotAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		heroEquipmentSlotBeforeUpsertMu.Lock()
		heroEquipmentSlotBeforeUpsertHooks = append(heroEquipmentSlotBeforeUpsertHooks, heroEquipmentSlotHook)
		heroEquipmentSlotBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		heroEquipmentSlotAfterUpsertMu.Lock()
		heroEquipmentSlotAfterUpsertHooks = append(heroEquipmentSlotAfterUpsertHooks, heroEquipmentSlotHook)
		heroEquipmentSlotAfterUpsertMu.Unlock()
	}
}

// OneG returns a single heroEquipmentSlot record from the query using the global executor.
func (q heroEquipmentSlotQuery) OneG(ctx context.Context) (*HeroEquipmentSlot, error) {
	return q.One(ctx, boil.GetContextDB())
}

// OneGP returns a single heroEquipmentSlot record from the query using the global executor, and panics on error.
func (q heroEquipmentSlotQuery) OneGP(ctx context.Context) *HeroEquipmentSlot {
	o, err := q.One(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single heroEquipmentSlot record from the query, and panics on error.
func (q heroEquipmentSlotQuery) OneP(ctx context.Context, exec boil.ContextExecutor) *HeroEquipmentSlot {
	o, err := q.One(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single heroEquipmentSlot record from the query.
func (q heroEquipmentSlotQuery) One(ctx context.Context, exec boil.ContextExecutor) (*HeroEquipmentSlot, error) {
	o := &HeroEquipmentSlot{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "game_runtime: failed to execute a one query for hero_equipment_slots")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all HeroEquipmentSlot records from the query using the global executor.
func (q heroEquipmentSlotQuery) AllG(ctx context.Context) (HeroEquipmentSlotSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// AllGP returns all HeroEquipmentSlot records from the query using the global executor, and panics on error.
func (q heroEquipmentSlotQuery) AllGP(ctx context.Context) HeroEquipmentSlotSlice {
	o, err := q.All(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all HeroEquipmentSlot records from the query, and panics on error.
func (q heroEquipmentSlotQuery) AllP(ctx context.Context, exec boil.ContextExecutor) HeroEquipmentSlotSlice {
	o, err := q.All(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all HeroEquipmentSlot records from the query.
func (q heroEquipmentSlotQuery) All(ctx context.Context, exec boil.ContextExecutor) (HeroEquipmentSlotSlice, error) {
	var o []*HeroEquipmentSlot

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "game_runtime: failed to assign all query results to HeroEquipmentSlot slice")
	}

	if len(heroEquipmentSlotAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all HeroEquipmentSlot records in the query using the global executor
func (q heroEquipmentSlotQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// CountGP returns the count of all HeroEquipmentSlot records in the query using the global executor, and panics on error.
func (q heroEquipmentSlotQuery) CountGP(ctx context.Context) int64 {
	c, err := q.Count(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all HeroEquipmentSlot records in the query, and panics on error.
func (q heroEquipmentSlotQuery) CountP(ctx context.Context, exec boil.ContextExecutor) int64 {
	c, err := q.Count(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all HeroEquipmentSlot records in the query.
func (q heroEquipmentSlotQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: failed to count hero_equipment_slots rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q heroEquipmentSlotQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q heroEquipmentSlotQuery) ExistsGP(ctx context.Context) bool {
	e, err := q.Exists(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q heroEquipmentSlotQuery) ExistsP(ctx context.Context, exec boil.ContextExecutor) bool {
	e, err := q.Exists(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q heroEquipmentSlotQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "game_runtime: failed to check if hero_equipment_slots exists")
	}

	return count > 0, nil
}

// AddedByItem pointed to by the foreign key.
func (o *HeroEquipmentSlot) AddedByItem(mods ...qm.QueryMod) playerItemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AddedByItemID),
	}

	queryMods = append(queryMods, mods...)

	return PlayerItems(queryMods...)
}

// EquippedItem pointed to by the foreign key.
func (o *HeroEquipmentSlot) EquippedItem(mods ...qm.QueryMod) playerItemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.EquippedItemID),
	}

	queryMods = append(queryMods, mods...)

	return PlayerItems(queryMods...)
}

// Hero pointed to by the foreign key.
func (o *HeroEquipmentSlot) Hero(mods ...qm.QueryMod) heroQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.HeroID),
	}

	queryMods = append(queryMods, mods...)

	return Heroes(queryMods...)
}

// LoadAddedByItem allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (heroEquipmentSlotL) LoadAddedByItem(ctx context.Context, e boil.ContextExecutor, singular bool, maybeHeroEquipmentSlot interface{}, mods queries.Applicator) error {
	var slice []*HeroEquipmentSlot
	var object *HeroEquipmentSlot

	if singular {
		var ok bool
		object, ok = maybeHeroEquipmentSlot.(*HeroEquipmentSlot)
		if !ok {
			object = new(HeroEquipmentSlot)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeHeroEquipmentSlot)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeHeroEquipmentSlot))
			}
		}
	} else {
		s, ok := maybeHeroEquipmentSlot.(*[]*HeroEquipmentSlot)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeHeroEquipmentSlot)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeHeroEquipmentSlot))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &heroEquipmentSlotR{}
		}
		if !queries.IsNil(object.AddedByItemID) {
			args[object.AddedByItemID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &heroEquipmentSlotR{}
			}

			if !queries.IsNil(obj.AddedByItemID) {
				args[obj.AddedByItemID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_runtime.player_items`),
		qm.WhereIn(`game_runtime.player_items.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_runtime.player_items.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PlayerItem")
	}

	var resultSlice []*PlayerItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PlayerItem")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for player_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for player_items")
	}

	if len(playerItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.AddedByItem = foreign
		if foreign.R == nil {
			foreign.R = &playerItemR{}
		}
		foreign.R.AddedByItemHeroEquipmentSlots = append(foreign.R.AddedByItemHeroEquipmentSlots, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AddedByItemID, foreign.ID) {
				local.R.AddedByItem = foreign
				if foreign.R == nil {
					foreign.R = &playerItemR{}
				}
				foreign.R.AddedByItemHeroEquipmentSlots = append(foreign.R.AddedByItemHeroEquipmentSlots, local)
				break
			}
		}
	}

	return nil
}

// LoadEquippedItem allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (heroEquipmentSlotL) LoadEquippedItem(ctx context.Context, e boil.ContextExecutor, singular bool, maybeHeroEquipmentSlot interface{}, mods queries.Applicator) error {
	var slice []*HeroEquipmentSlot
	var object *HeroEquipmentSlot

	if singular {
		var ok bool
		object, ok = maybeHeroEquipmentSlot.(*HeroEquipmentSlot)
		if !ok {
			object = new(HeroEquipmentSlot)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeHeroEquipmentSlot)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeHeroEquipmentSlot))
			}
		}
	} else {
		s, ok := maybeHeroEquipmentSlot.(*[]*HeroEquipmentSlot)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeHeroEquipmentSlot)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeHeroEquipmentSlot))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &heroEquipmentSlotR{}
		}
		if !queries.IsNil(object.EquippedItemID) {
			args[object.EquippedItemID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &heroEquipmentSlotR{}
			}

			if !queries.IsNil(obj.EquippedItemID) {
				args[obj.EquippedItemID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_runtime.player_items`),
		qm.WhereIn(`game_runtime.player_items.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_runtime.player_items.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PlayerItem")
	}

	var resultSlice []*PlayerItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PlayerItem")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for player_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for player_items")
	}

	if len(playerItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EquippedItem = foreign
		if foreign.R == nil {
			foreign.R = &playerItemR{}
		}
		foreign.R.EquippedItemHeroEquipmentSlots = append(foreign.R.EquippedItemHeroEquipmentSlots, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.EquippedItemID, foreign.ID) {
				local.R.EquippedItem = foreign
				if foreign.R == nil {
					foreign.R = &playerItemR{}
				}
				foreign.R.EquippedItemHeroEquipmentSlots = append(foreign.R.EquippedItemHeroEquipmentSlots, local)
				break
			}
		}
	}

	return nil
}

// LoadHero allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (heroEquipmentSlotL) LoadHero(ctx context.Context, e boil.ContextExecutor, singular bool, maybeHeroEquipmentSlot interface{}, mods queries.Applicator) error {
	var slice []*HeroEquipmentSlot
	var object *HeroEquipmentSlot

	if singular {
		var ok bool
		object, ok = maybeHeroEquipmentSlot.(*HeroEquipmentSlot)
		if !ok {
			object = new(HeroEquipmentSlot)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeHeroEquipmentSlot)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeHeroEquipmentSlot))
			}
		}
	} else {
		s, ok := maybeHeroEquipmentSlot.(*[]*HeroEquipmentSlot)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeHeroEquipmentSlot)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeHeroEquipmentSlot))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &heroEquipmentSlotR{}
		}
		args[object.HeroID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &heroEquipmentSlotR{}
			}

			args[obj.HeroID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_runtime.heroes`),
		qm.WhereIn(`game_runtime.heroes.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`game_runtime.heroes.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Hero")
	}

	var resultSlice []*Hero
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Hero")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for heroes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for heroes")
	}

	if len(heroAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Hero = foreign
		if foreign.R == nil {
			foreign.R = &heroR{}
		}
		foreign.R.HeroEquipmentSlots = append(foreign.R.HeroEquipmentSlots, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.HeroID == foreign.ID {
				local.R.Hero = foreign
				if foreign.R == nil {
					foreign.R = &heroR{}
				}
				foreign.R.HeroEquipmentSlots = append(foreign.R.HeroEquipmentSlots, local)
				break
			}
		}
	}

	return nil
}

// SetAddedByItemG of the heroEquipmentSlot to the related item.
// Sets o.R.AddedByItem to related.
// Adds o to related.R.AddedByItemHeroEquipmentSlots.
// Uses the global database handle.
func (o *HeroEquipmentSlot) SetAddedByItemG(ctx context.Context, insert bool, related *PlayerItem) error {
	return o.SetAddedByItem(ctx, boil.GetContextDB(), insert, related)
}

// SetAddedByItemP of the heroEquipmentSlot to the related item.
// Sets o.R.AddedByItem to related.
// Adds o to related.R.AddedByItemHeroEquipmentSlots.
// Panics on error.
func (o *HeroEquipmentSlot) SetAddedByItemP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PlayerItem) {
	if err := o.SetAddedByItem(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAddedByItemGP of the heroEquipmentSlot to the related item.
// Sets o.R.AddedByItem to related.
// Adds o to related.R.AddedByItemHeroEquipmentSlots.
// Uses the global database handle and panics on error.
func (o *HeroEquipmentSlot) SetAddedByItemGP(ctx context.Context, insert bool, related *PlayerItem) {
	if err := o.SetAddedByItem(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetAddedByItem of the heroEquipmentSlot to the related item.
// Sets o.R.AddedByItem to related.
// Adds o to related.R.AddedByItemHeroEquipmentSlots.
func (o *HeroEquipmentSlot) SetAddedByItem(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PlayerItem) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"game_runtime\".\"hero_equipment_slots\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"added_by_item_id"}),
		strmangle.WhereClause("\"", "\"", 2, heroEquipmentSlotPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AddedByItemID, related.ID)
	if o.R == nil {
		o.R = &heroEquipmentSlotR{
			AddedByItem: related,
		}
	} else {
		o.R.AddedByItem = related
	}

	if related.R == nil {
		related.R = &playerItemR{
			AddedByItemHeroEquipmentSlots: HeroEquipmentSlotSlice{o},
		}
	} else {
		related.R.AddedByItemHeroEquipmentSlots = append(related.R.AddedByItemHeroEquipmentSlots, o)
	}

	return nil
}

// RemoveAddedByItemG relationship.
// Sets o.R.AddedByItem to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *HeroEquipmentSlot) RemoveAddedByItemG(ctx context.Context, related *PlayerItem) error {
	return o.RemoveAddedByItem(ctx, boil.GetContextDB(), related)
}

// RemoveAddedByItemP relationship.
// Sets o.R.AddedByItem to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *HeroEquipmentSlot) RemoveAddedByItemP(ctx context.Context, exec boil.ContextExecutor, related *PlayerItem) {
	if err := o.RemoveAddedByItem(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveAddedByItemGP relationship.
// Sets o.R.AddedByItem to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *HeroEquipmentSlot) RemoveAddedByItemGP(ctx context.Context, related *PlayerItem) {
	if err := o.RemoveAddedByItem(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveAddedByItem relationship.
// Sets o.R.AddedByItem to nil.
// Removes o from all passed in related items' relationships struct.
func (o *HeroEquipmentSlot) RemoveAddedByItem(ctx context.Context, exec boil.ContextExecutor, related *PlayerItem) error {
	var err error

	queries.SetScanner(&o.AddedByItemID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("added_by_item_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.AddedByItem = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.AddedByItemHeroEquipmentSlots {
		if queries.Equal(o.AddedByItemID, ri.AddedByItemID) {
			continue
		}

		ln := len(related.R.AddedByItemHeroEquipmentSlots)
		if ln > 1 && i < ln-1 {
			related.R.AddedByItemHeroEquipmentSlots[i] = related.R.AddedByItemHeroEquipmentSlots[ln-1]
		}
		related.R.AddedByItemHeroEquipmentSlots = related.R.AddedByItemHeroEquipmentSlots[:ln-1]
		break
	}
	return nil
}

// SetEquippedItemG of the heroEquipmentSlot to the related item.
// Sets o.R.EquippedItem to related.
// Adds o to related.R.EquippedItemHeroEquipmentSlots.
// Uses the global database handle.
func (o *HeroEquipmentSlot) SetEquippedItemG(ctx context.Context, insert bool, related *PlayerItem) error {
	return o.SetEquippedItem(ctx, boil.GetContextDB(), insert, related)
}

// SetEquippedItemP of the heroEquipmentSlot to the related item.
// Sets o.R.EquippedItem to related.
// Adds o to related.R.EquippedItemHeroEquipmentSlots.
// Panics on error.
func (o *HeroEquipmentSlot) SetEquippedItemP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PlayerItem) {
	if err := o.SetEquippedItem(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEquippedItemGP of the heroEquipmentSlot to the related item.
// Sets o.R.EquippedItem to related.
// Adds o to related.R.EquippedItemHeroEquipmentSlots.
// Uses the global database handle and panics on error.
func (o *HeroEquipmentSlot) SetEquippedItemGP(ctx context.Context, insert bool, related *PlayerItem) {
	if err := o.SetEquippedItem(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetEquippedItem of the heroEquipmentSlot to the related item.
// Sets o.R.EquippedItem to related.
// Adds o to related.R.EquippedItemHeroEquipmentSlots.
func (o *HeroEquipmentSlot) SetEquippedItem(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PlayerItem) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"game_runtime\".\"hero_equipment_slots\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"equipped_item_id"}),
		strmangle.WhereClause("\"", "\"", 2, heroEquipmentSlotPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.EquippedItemID, related.ID)
	if o.R == nil {
		o.R = &heroEquipmentSlotR{
			EquippedItem: related,
		}
	} else {
		o.R.EquippedItem = related
	}

	if related.R == nil {
		related.R = &playerItemR{
			EquippedItemHeroEquipmentSlots: HeroEquipmentSlotSlice{o},
		}
	} else {
		related.R.EquippedItemHeroEquipmentSlots = append(related.R.EquippedItemHeroEquipmentSlots, o)
	}

	return nil
}

// RemoveEquippedItemG relationship.
// Sets o.R.EquippedItem to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *HeroEquipmentSlot) RemoveEquippedItemG(ctx context.Context, related *PlayerItem) error {
	return o.RemoveEquippedItem(ctx, boil.GetContextDB(), related)
}

// RemoveEquippedItemP relationship.
// Sets o.R.EquippedItem to nil.
// Removes o from all passed in related items' relationships struct.
// Panics on error.
func (o *HeroEquipmentSlot) RemoveEquippedItemP(ctx context.Context, exec boil.ContextExecutor, related *PlayerItem) {
	if err := o.RemoveEquippedItem(ctx, exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveEquippedItemGP relationship.
// Sets o.R.EquippedItem to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle and panics on error.
func (o *HeroEquipmentSlot) RemoveEquippedItemGP(ctx context.Context, related *PlayerItem) {
	if err := o.RemoveEquippedItem(ctx, boil.GetContextDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveEquippedItem relationship.
// Sets o.R.EquippedItem to nil.
// Removes o from all passed in related items' relationships struct.
func (o *HeroEquipmentSlot) RemoveEquippedItem(ctx context.Context, exec boil.ContextExecutor, related *PlayerItem) error {
	var err error

	queries.SetScanner(&o.EquippedItemID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("equipped_item_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.EquippedItem = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.EquippedItemHeroEquipmentSlots {
		if queries.Equal(o.EquippedItemID, ri.EquippedItemID) {
			continue
		}

		ln := len(related.R.EquippedItemHeroEquipmentSlots)
		if ln > 1 && i < ln-1 {
			related.R.EquippedItemHeroEquipmentSlots[i] = related.R.EquippedItemHeroEquipmentSlots[ln-1]
		}
		related.R.EquippedItemHeroEquipmentSlots = related.R.EquippedItemHeroEquipmentSlots[:ln-1]
		break
	}
	return nil
}

// SetHeroG of the heroEquipmentSlot to the related item.
// Sets o.R.Hero to related.
// Adds o to related.R.HeroEquipmentSlots.
// Uses the global database handle.
func (o *HeroEquipmentSlot) SetHeroG(ctx context.Context, insert bool, related *Hero) error {
	return o.SetHero(ctx, boil.GetContextDB(), insert, related)
}

// SetHeroP of the heroEquipmentSlot to the related item.
// Sets o.R.Hero to related.
// Adds o to related.R.HeroEquipmentSlots.
// Panics on error.
func (o *HeroEquipmentSlot) SetHeroP(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Hero) {
	if err := o.SetHero(ctx, exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetHeroGP of the heroEquipmentSlot to the related item.
// Sets o.R.Hero to related.
// Adds o to related.R.HeroEquipmentSlots.
// Uses the global database handle and panics on error.
func (o *HeroEquipmentSlot) SetHeroGP(ctx context.Context, insert bool, related *Hero) {
	if err := o.SetHero(ctx, boil.GetContextDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetHero of the heroEquipmentSlot to the related item.
// Sets o.R.Hero to related.
// Adds o to related.R.HeroEquipmentSlots.
func (o *HeroEquipmentSlot) SetHero(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Hero) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"game_runtime\".\"hero_equipment_slots\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"hero_id"}),
		strmangle.WhereClause("\"", "\"", 2, heroEquipmentSlotPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.HeroID = related.ID
	if o.R == nil {
		o.R = &heroEquipmentSlotR{
			Hero: related,
		}
	} else {
		o.R.Hero = related
	}

	if related.R == nil {
		related.R = &heroR{
			HeroEquipmentSlots: HeroEquipmentSlotSlice{o},
		}
	} else {
		related.R.HeroEquipmentSlots = append(related.R.HeroEquipmentSlots, o)
	}

	return nil
}

// HeroEquipmentSlots retrieves all the records using an executor.
func HeroEquipmentSlots(mods ...qm.QueryMod) heroEquipmentSlotQuery {
	mods = append(mods, qm.From("\"game_runtime\".\"hero_equipment_slots\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"game_runtime\".\"hero_equipment_slots\".*"})
	}

	return heroEquipmentSlotQuery{q}
}

// FindHeroEquipmentSlotG retrieves a single record by ID.
func FindHeroEquipmentSlotG(ctx context.Context, iD string, selectCols ...string) (*HeroEquipmentSlot, error) {
	return FindHeroEquipmentSlot(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindHeroEquipmentSlotP retrieves a single record by ID with an executor, and panics on error.
func FindHeroEquipmentSlotP(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) *HeroEquipmentSlot {
	retobj, err := FindHeroEquipmentSlot(ctx, exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindHeroEquipmentSlotGP retrieves a single record by ID, and panics on error.
func FindHeroEquipmentSlotGP(ctx context.Context, iD string, selectCols ...string) *HeroEquipmentSlot {
	retobj, err := FindHeroEquipmentSlot(ctx, boil.GetContextDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindHeroEquipmentSlot retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHeroEquipmentSlot(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*HeroEquipmentSlot, error) {
	heroEquipmentSlotObj := &HeroEquipmentSlot{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"game_runtime\".\"hero_equipment_slots\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, heroEquipmentSlotObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "game_runtime: unable to select from hero_equipment_slots")
	}

	if err = heroEquipmentSlotObj.doAfterSelectHooks(ctx, exec); err != nil {
		return heroEquipmentSlotObj, err
	}

	return heroEquipmentSlotObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *HeroEquipmentSlot) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *HeroEquipmentSlot) InsertP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) {
	if err := o.Insert(ctx, exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *HeroEquipmentSlot) InsertGP(ctx context.Context, columns boil.Columns) {
	if err := o.Insert(ctx, boil.GetContextDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *HeroEquipmentSlot) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("game_runtime: no hero_equipment_slots provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(heroEquipmentSlotColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	heroEquipmentSlotInsertCacheMut.RLock()
	cache, cached := heroEquipmentSlotInsertCache[key]
	heroEquipmentSlotInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			heroEquipmentSlotAllColumns,
			heroEquipmentSlotColumnsWithDefault,
			heroEquipmentSlotColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(heroEquipmentSlotType, heroEquipmentSlotMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(heroEquipmentSlotType, heroEquipmentSlotMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"game_runtime\".\"hero_equipment_slots\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"game_runtime\".\"hero_equipment_slots\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "game_runtime: unable to insert into hero_equipment_slots")
	}

	if !cached {
		heroEquipmentSlotInsertCacheMut.Lock()
		heroEquipmentSlotInsertCache[key] = cache
		heroEquipmentSlotInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single HeroEquipmentSlot record using the global executor.
// See Update for more documentation.
func (o *HeroEquipmentSlot) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// UpdateP uses an executor to update the HeroEquipmentSlot, and panics on error.
// See Update for more documentation.
func (o *HeroEquipmentSlot) UpdateP(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateGP a single HeroEquipmentSlot record using the global executor. Panics on error.
// See Update for more documentation.
func (o *HeroEquipmentSlot) UpdateGP(ctx context.Context, columns boil.Columns) int64 {
	rowsAff, err := o.Update(ctx, boil.GetContextDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Update uses an executor to update the HeroEquipmentSlot.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *HeroEquipmentSlot) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	heroEquipmentSlotUpdateCacheMut.RLock()
	cache, cached := heroEquipmentSlotUpdateCache[key]
	heroEquipmentSlotUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			heroEquipmentSlotAllColumns,
			heroEquipmentSlotPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("game_runtime: unable to update hero_equipment_slots, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"game_runtime\".\"hero_equipment_slots\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, heroEquipmentSlotPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(heroEquipmentSlotType, heroEquipmentSlotMapping, append(wl, heroEquipmentSlotPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to update hero_equipment_slots row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: failed to get rows affected by update for hero_equipment_slots")
	}

	if !cached {
		heroEquipmentSlotUpdateCacheMut.Lock()
		heroEquipmentSlotUpdateCache[key] = cache
		heroEquipmentSlotUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q heroEquipmentSlotQuery) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllG updates all rows with the specified column values.
func (q heroEquipmentSlotQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (q heroEquipmentSlotQuery) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := q.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values.
func (q heroEquipmentSlotQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to update all for hero_equipment_slots")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to retrieve rows affected for hero_equipment_slots")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o HeroEquipmentSlotSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o HeroEquipmentSlotSlice) UpdateAllGP(ctx context.Context, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, boil.GetContextDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o HeroEquipmentSlotSlice) UpdateAllP(ctx context.Context, exec boil.ContextExecutor, cols M) int64 {
	rowsAff, err := o.UpdateAll(ctx, exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HeroEquipmentSlotSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("game_runtime: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), heroEquipmentSlotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"game_runtime\".\"hero_equipment_slots\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, heroEquipmentSlotPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to update all in heroEquipmentSlot slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to retrieve rows affected all in update all heroEquipmentSlot")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *HeroEquipmentSlot) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *HeroEquipmentSlot) UpsertGP(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *HeroEquipmentSlot) UpsertP(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) {
	if err := o.Upsert(ctx, exec, updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *HeroEquipmentSlot) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("game_runtime: no hero_equipment_slots provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(heroEquipmentSlotColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	heroEquipmentSlotUpsertCacheMut.RLock()
	cache, cached := heroEquipmentSlotUpsertCache[key]
	heroEquipmentSlotUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			heroEquipmentSlotAllColumns,
			heroEquipmentSlotColumnsWithDefault,
			heroEquipmentSlotColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			heroEquipmentSlotAllColumns,
			heroEquipmentSlotPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("game_runtime: unable to upsert hero_equipment_slots, could not build update column list")
		}

		ret := strmangle.SetComplement(heroEquipmentSlotAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(heroEquipmentSlotPrimaryKeyColumns) == 0 {
				return errors.New("game_runtime: unable to upsert hero_equipment_slots, could not build conflict column list")
			}

			conflict = make([]string, len(heroEquipmentSlotPrimaryKeyColumns))
			copy(conflict, heroEquipmentSlotPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"game_runtime\".\"hero_equipment_slots\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(heroEquipmentSlotType, heroEquipmentSlotMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(heroEquipmentSlotType, heroEquipmentSlotMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "game_runtime: unable to upsert hero_equipment_slots")
	}

	if !cached {
		heroEquipmentSlotUpsertCacheMut.Lock()
		heroEquipmentSlotUpsertCache[key] = cache
		heroEquipmentSlotUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single HeroEquipmentSlot record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *HeroEquipmentSlot) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// DeleteP deletes a single HeroEquipmentSlot record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *HeroEquipmentSlot) DeleteP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.Delete(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteGP deletes a single HeroEquipmentSlot record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *HeroEquipmentSlot) DeleteGP(ctx context.Context) int64 {
	rowsAff, err := o.Delete(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// Delete deletes a single HeroEquipmentSlot record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HeroEquipmentSlot) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("game_runtime: no HeroEquipmentSlot provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), heroEquipmentSlotPrimaryKeyMapping)
	sql := "DELETE FROM \"game_runtime\".\"hero_equipment_slots\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to delete from hero_equipment_slots")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: failed to get rows affected by delete for hero_equipment_slots")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q heroEquipmentSlotQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows, and panics on error.
func (q heroEquipmentSlotQuery) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := q.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows, and panics on error.
func (q heroEquipmentSlotQuery) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := q.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all matching rows.
func (q heroEquipmentSlotQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("game_runtime: no heroEquipmentSlotQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to delete all from hero_equipment_slots")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: failed to get rows affected by deleteall for hero_equipment_slots")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o HeroEquipmentSlotSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o HeroEquipmentSlotSlice) DeleteAllP(ctx context.Context, exec boil.ContextExecutor) int64 {
	rowsAff, err := o.DeleteAll(ctx, exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o HeroEquipmentSlotSlice) DeleteAllGP(ctx context.Context) int64 {
	rowsAff, err := o.DeleteAll(ctx, boil.GetContextDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return rowsAff
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HeroEquipmentSlotSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(heroEquipmentSlotBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), heroEquipmentSlotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"game_runtime\".\"hero_equipment_slots\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, heroEquipmentSlotPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: unable to delete all from heroEquipmentSlot slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "game_runtime: failed to get rows affected by deleteall for hero_equipment_slots")
	}

	if len(heroEquipmentSlotAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *HeroEquipmentSlot) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("game_runtime: no HeroEquipmentSlot provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *HeroEquipmentSlot) ReloadP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.Reload(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *HeroEquipmentSlot) ReloadGP(ctx context.Context) {
	if err := o.Reload(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HeroEquipmentSlot) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindHeroEquipmentSlot(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HeroEquipmentSlotSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("game_runtime: empty HeroEquipmentSlotSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *HeroEquipmentSlotSlice) ReloadAllP(ctx context.Context, exec boil.ContextExecutor) {
	if err := o.ReloadAll(ctx, exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *HeroEquipmentSlotSlice) ReloadAllGP(ctx context.Context) {
	if err := o.ReloadAll(ctx, boil.GetContextDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HeroEquipmentSlotSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HeroEquipmentSlotSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), heroEquipmentSlotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"game_runtime\".\"hero_equipment_slots\".* FROM \"game_runtime\".\"hero_equipment_slots\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, heroEquipmentSlotPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "game_runtime: unable to reload all in HeroEquipmentSlotSlice")
	}

	*o = slice

	return nil
}

// HeroEquipmentSlotExistsG checks if the HeroEquipmentSlot row exists.
func HeroEquipmentSlotExistsG(ctx context.Context, iD string) (bool, error) {
	return HeroEquipmentSlotExists(ctx, boil.GetContextDB(), iD)
}

// HeroEquipmentSlotExistsP checks if the HeroEquipmentSlot row exists. Panics on error.
func HeroEquipmentSlotExistsP(ctx context.Context, exec boil.ContextExecutor, iD string) bool {
	e, err := HeroEquipmentSlotExists(ctx, exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// HeroEquipmentSlotExistsGP checks if the HeroEquipmentSlot row exists. Panics on error.
func HeroEquipmentSlotExistsGP(ctx context.Context, iD string) bool {
	e, err := HeroEquipmentSlotExists(ctx, boil.GetContextDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// HeroEquipmentSlotExists checks if the HeroEquipmentSlot row exists.
func HeroEquipmentSlotExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"game_runtime\".\"hero_equipment_slots\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "game_runtime: unable to check if hero_equipment_slots exists")
	}

	return exists, nil
}

// Exists checks if the HeroEquipmentSlot row exists.
func (o *HeroEquipmentSlot) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return HeroEquipmentSlotExists(ctx, exec, o.ID)
}
