# infra/ory/oathkeeper/oathkeeper.yml (Corrected Version)

version: v0.40.8

serve:
  proxy:
    port: 4456
  api:
    port: 4457

errors:
  handlers:
    # Handler 1: For API clients that want JSON
    json:
      enabled: true
      config: {}

    # Handler 2: For browsers that need to be redirected
    redirect:
      enabled: true
      config:
        to: http://127.0.0.1/user/ # Your UI's login page

access_rules:
  repositories:
    - file:///etc/config/oathkeeper/access-rules.json

authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: http://tsu_kratos_service:4433/sessions/whoami
      preserve_query: true
      preserve_path: true
  bearer_token:
    enabled: true
    config:
      check_session_url: http://tsu_kratos_service:4433/sessions/whoami
      preserve_query: true
      preserve_path: true
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

mutators:
  noop:
    enabled: true
  header:
    enabled: true
    config:
      headers:
        X-Session-Token: '{{ print .Extra.ory_kratos_session }}'
        X-User-ID: '{{ print .Subject }}'